INSERT INTO `cities` (`name`, `state_id`, `created`, `updated`) VALUES
('Guanajuato','11', NOW(), NOW() ),
('Silao','11', NOW(), NOW() ),
('Romita','11', NOW(), NOW() ),
('San Francisco del Rincón','11', NOW(), NOW() ),
('Purísima del Rincón','11', NOW(), NOW() ),
('Manuel Doblado','11', NOW(), NOW() ),
('Irapuato','11', NOW(), NOW() ),
('Salamanca','11', NOW(), NOW() ),
('Pueblo Nuevo','11', NOW(), NOW() ),
('Pénjamo','11', NOW(), NOW() ),
('Cuerámaro','11', NOW(), NOW() ),
('Abasolo','11', NOW(), NOW() ),
('Huanímaro','11', NOW(), NOW() ),
('León','11', NOW(), NOW() ),
('San Felipe','11', NOW(), NOW() ),
('Ocampo','11', NOW(), NOW() ),
('San Miguel de Allende','11', NOW(), NOW() ),
('Dolores Hidalgo Cuna de la Independencia Nacional','11', NOW(), NOW() ),
('San Diego de la Unión','11', NOW(), NOW() ),
('San Luis de la Paz','11', NOW(), NOW() ),
('Victoria','11', NOW(), NOW() ),
('Xichú','11', NOW(), NOW() ),
('Atarjea','11', NOW(), NOW() ),
('Santa Catarina','11', NOW(), NOW() ),
('Doctor Mora','11', NOW(), NOW() ),
('Tierra Blanca','11', NOW(), NOW() ),
('San José Iturbide','11', NOW(), NOW() ),
('Celaya','11', NOW(), NOW() ),
('Apaseo el Grande','11', NOW(), NOW() ),
('Comonfort','11', NOW(), NOW() ),
('Santa Cruz de Juventino Rosas','11', NOW(), NOW() ),
('Villagrán','11', NOW(), NOW() ),
('Cortazar','11', NOW(), NOW() ),
('Valle de Santiago','11', NOW(), NOW() ),
('Jaral del Progreso','11', NOW(), NOW() ),
('Apaseo el Alto','11', NOW(), NOW() ),
('Jerécuaro','11', NOW(), NOW() ),
('Coroneo','11', NOW(), NOW() ),
('Acámbaro','11', NOW(), NOW() ),
('Tarimoro','11', NOW(), NOW() ),
('Tarandacuao','11', NOW(), NOW() ),
('Moroleón','11', NOW(), NOW() ),
('Salvatierra','11', NOW(), NOW() ),
('Yuriria','11', NOW(), NOW() ),
('Santiago Maravatío','11', NOW(), NOW() ),
('Uriangato','11', NOW(), NOW() ),
('Cuernavaca','17', NOW(), NOW() ),
('Huitzilac','17', NOW(), NOW() ),
('Tepoztlán','17', NOW(), NOW() ),
('Tlalnepantla','17', NOW(), NOW() ),
('Tlayacapan','17', NOW(), NOW() ),
('Jiutepec','17', NOW(), NOW() ),
('Temixco','17', NOW(), NOW() ),
('Miacatlán','17', NOW(), NOW() ),
('Coatlán del Río','17', NOW(), NOW() ),
('Tetecala','17', NOW(), NOW() ),
('Mazatepec','17', NOW(), NOW() ),
('Amacuzac','17', NOW(), NOW() ),
('Puente de Ixtla','17', NOW(), NOW() ),
('Ayala','17', NOW(), NOW() ),
('Yautepec','17', NOW(), NOW() ),
('Cuautla','17', NOW(), NOW() ),
('Emiliano Zapata','17', NOW(), NOW() ),
('Tlaltizapán','17', NOW(), NOW() ),
('Zacatepec','17', NOW(), NOW() ),
('Xochitepec','17', NOW(), NOW() ),
('Tetela del Volcán','17', NOW(), NOW() ),
('Yecapixtla','17', NOW(), NOW() ),
('Totolapan','17', NOW(), NOW() ),
('Atlatlahucan','17', NOW(), NOW() ),
('Ocuituco','17', NOW(), NOW() ),
('Temoac','17', NOW(), NOW() ),
('Zacualpan','17', NOW(), NOW() ),
('Jojutla','17', NOW(), NOW() ),
('Tepalcingo','17', NOW(), NOW() ),
('Jonacatepec','17', NOW(), NOW() ),
('Axochiapan','17', NOW(), NOW() ),
('Jantetelco','17', NOW(), NOW() ),
('Tlaquiltenango','17', NOW(), NOW() ),
('Culiacán','25', NOW(), NOW() ),
('Navolato','25', NOW(), NOW() ),
('Badiraguato','25', NOW(), NOW() ),
('Cosalá','25', NOW(), NOW() ),
('Mocorito','25', NOW(), NOW() ),
('Guasave','25', NOW(), NOW() ),
('Ahome','25', NOW(), NOW() ),
('Salvador Alvarado','25', NOW(), NOW() ),
('Angostura','25', NOW(), NOW() ),
('Choix','25', NOW(), NOW() ),
('El Fuerte','25', NOW(), NOW() ),
('Sinaloa','25', NOW(), NOW() ),
('Mazatlán','25', NOW(), NOW() ),
('Escuinapa','25', NOW(), NOW() ),
('Concordia','25', NOW(), NOW() ),
('Elota','25', NOW(), NOW() ),
('Rosario','25', NOW(), NOW() ),
('San Ignacio','25', NOW(), NOW() ),
('Guadalajara','14', NOW(), NOW() ),
('Zapopan','14', NOW(), NOW() ),
('San Cristóbal de la Barranca','14', NOW(), NOW() ),
('Ixtlahuacán del Río','14', NOW(), NOW() ),
('Tala','14', NOW(), NOW() ),
('El Arenal','14', NOW(), NOW() ),
('Amatitán','14', NOW(), NOW() ),
('Tonalá','14', NOW(), NOW() ),
('Zapotlanejo','14', NOW(), NOW() ),
('Acatic','14', NOW(), NOW() ),
('Cuquío','14', NOW(), NOW() ),
('Tlaquepaque','14', NOW(), NOW() ),
('Tlajomulco de Zúñiga','14', NOW(), NOW() ),
('El Salto','14', NOW(), NOW() ),
('Acatlán de Juárez','14', NOW(), NOW() ),
('Villa Corona','14', NOW(), NOW() ),
('Zacoalco de Torres','14', NOW(), NOW() ),
('Atemajac de Brizuela','14', NOW(), NOW() ),
('Jocotepec','14', NOW(), NOW() ),
('Ixtlahuacán de los Membrillos','14', NOW(), NOW() ),
('Juanacatlán','14', NOW(), NOW() ),
('Chapala','14', NOW(), NOW() ),
('Poncitlán','14', NOW(), NOW() ),
('Zapotlán del Rey','14', NOW(), NOW() ),
('Huejuquilla el Alto','14', NOW(), NOW() ),
('Mezquitic','14', NOW(), NOW() ),
('Villa Guerrero','14', NOW(), NOW() ),
('Bolaños','14', NOW(), NOW() ),
('Totatiche','14', NOW(), NOW() ),
('Colotlán','14', NOW(), NOW() ),
('Santa María de los Ángeles','14', NOW(), NOW() ),
('Huejúcar','14', NOW(), NOW() ),
('Chimaltitán','14', NOW(), NOW() ),
('San Martín de Bolaños','14', NOW(), NOW() ),
('Tequila','14', NOW(), NOW() ),
('Hostotipaquillo','14', NOW(), NOW() ),
('Magdalena','14', NOW(), NOW() ),
('Etzatlán','14', NOW(), NOW() ),
('San Marcos','14', NOW(), NOW() ),
('San Juanito de Escobedo','14', NOW(), NOW() ),
('Ameca','14', NOW(), NOW() ),
('Ahualulco de Mercado','14', NOW(), NOW() ),
('Teuchitlán','14', NOW(), NOW() ),
('San Martín Hidalgo','14', NOW(), NOW() ),
('Guachinango','14', NOW(), NOW() ),
('Mixtlán','14', NOW(), NOW() ),
('Mascota','14', NOW(), NOW() ),
('San Sebastián del Oeste','14', NOW(), NOW() ),
('San Juan de los Lagos','14', NOW(), NOW() ),
('Jalostotitlán','14', NOW(), NOW() ),
('San Miguel el Alto','14', NOW(), NOW() ),
('San Julián','14', NOW(), NOW() ),
('Arandas','14', NOW(), NOW() ),
('San Ignacio Cerro Gordo','14', NOW(), NOW() ),
('Teocaltiche','14', NOW(), NOW() ),
('Villa Hidalgo','14', NOW(), NOW() ),
('Encarnación de Díaz','14', NOW(), NOW() ),
('Yahualica de González Gallo','14', NOW(), NOW() ),
('Mexticacán','14', NOW(), NOW() ),
('Cañadas de Obregón','14', NOW(), NOW() ),
('Valle de Guadalupe','14', NOW(), NOW() ),
('Lagos de Moreno','14', NOW(), NOW() ),
('Ojuelos de Jalisco','14', NOW(), NOW() ),
('Unión de San Antonio','14', NOW(), NOW() ),
('San Diego de Alejandría','14', NOW(), NOW() ),
('Tepatitlán de Morelos','14', NOW(), NOW() ),
('Tototlán','14', NOW(), NOW() ),
('Atotonilco el Alto','14', NOW(), NOW() ),
('Ocotlán','14', NOW(), NOW() ),
('Jamay','14', NOW(), NOW() ),
('La Barca','14', NOW(), NOW() ),
('Ayotlán','14', NOW(), NOW() ),
('Jesús María','14', NOW(), NOW() ),
('Degollado','14', NOW(), NOW() ),
('Unión de Tula','14', NOW(), NOW() ),
('Ayutla','14', NOW(), NOW() ),
('Atenguillo','14', NOW(), NOW() ),
('Cuautla','14', NOW(), NOW() ),
('Atengo','14', NOW(), NOW() ),
('Talpa de Allende','14', NOW(), NOW() ),
('Puerto Vallarta','14', NOW(), NOW() ),
('Cabo Corrientes','14', NOW(), NOW() ),
('Tomatlán','14', NOW(), NOW() ),
('Cocula','14', NOW(), NOW() ),
('Tecolotlán','14', NOW(), NOW() ),
('Tenamaxtlán','14', NOW(), NOW() ),
('Juchitlán','14', NOW(), NOW() ),
('Chiquilistlán','14', NOW(), NOW() ),
('Ejutla','14', NOW(), NOW() ),
('El Limón','14', NOW(), NOW() ),
('El Grullo','14', NOW(), NOW() ),
('Tonaya','14', NOW(), NOW() ),
('Tuxcacuesco','14', NOW(), NOW() ),
('Villa Purificación','14', NOW(), NOW() ),
('La Huerta','14', NOW(), NOW() ),
('Autlán de Navarro','14', NOW(), NOW() ),
('Casimiro Castillo','14', NOW(), NOW() ),
('Cuautitlán de García Barragán','14', NOW(), NOW() ),
('Cihuatlán','14', NOW(), NOW() ),
('Zapotlán el Grande','14', NOW(), NOW() ),
('Gómez Farías','14', NOW(), NOW() ),
('Concepción de Buenos Aires','14', NOW(), NOW() ),
('Atoyac','14', NOW(), NOW() ),
('Techaluta de Montenegro','14', NOW(), NOW() ),
('Teocuitatlán de Corona','14', NOW(), NOW() ),
('Sayula','14', NOW(), NOW() ),
('Tapalpa','14', NOW(), NOW() ),
('Amacueca','14', NOW(), NOW() ),
('Tizapán el Alto','14', NOW(), NOW() ),
('Tuxcueca','14', NOW(), NOW() ),
('La Manzanilla de la Paz','14', NOW(), NOW() ),
('Mazamitla','14', NOW(), NOW() ),
('Valle de Juárez','14', NOW(), NOW() ),
('Quitupan','14', NOW(), NOW() ),
('Zapotiltic','14', NOW(), NOW() ),
('Tamazula de Gordiano','14', NOW(), NOW() ),
('San Gabriel','14', NOW(), NOW() ),
('Tolimán','14', NOW(), NOW() ),
('Zapotitlán de Vadillo','14', NOW(), NOW() ),
('Tuxpan','14', NOW(), NOW() ),
('Tonila','14', NOW(), NOW() ),
('Pihuamo','14', NOW(), NOW() ),
('Tecalitlán','14', NOW(), NOW() ),
('Jilotlán de los Dolores','14', NOW(), NOW() ),
('Santa María del Oro','14', NOW(), NOW() ),
('Saltillo','5', NOW(), NOW() ),
('Arteaga','5', NOW(), NOW() ),
('Juárez','5', NOW(), NOW() ),
('Progreso','5', NOW(), NOW() ),
('Escobedo','5', NOW(), NOW() ),
('San Buenaventura','5', NOW(), NOW() ),
('Abasolo','5', NOW(), NOW() ),
('Candela','5', NOW(), NOW() ),
('Frontera','5', NOW(), NOW() ),
('Monclova','5', NOW(), NOW() ),
('Castaños','5', NOW(), NOW() ),
('Ramos Arizpe','5', NOW(), NOW() ),
('General Cepeda','5', NOW(), NOW() ),
('Piedras Negras','5', NOW(), NOW() ),
('Nava','5', NOW(), NOW() ),
('Acuña','5', NOW(), NOW() ),
('Múzquiz','5', NOW(), NOW() ),
('Jiménez','5', NOW(), NOW() ),
('Zaragoza','5', NOW(), NOW() ),
('Morelos','5', NOW(), NOW() ),
('Allende','5', NOW(), NOW() ),
('Villa Unión','5', NOW(), NOW() ),
('Guerrero','5', NOW(), NOW() ),
('Hidalgo','5', NOW(), NOW() ),
('Sabinas','5', NOW(), NOW() ),
('San Juan de Sabinas','5', NOW(), NOW() ),
('Torreón','5', NOW(), NOW() ),
('Matamoros','5', NOW(), NOW() ),
('Viesca','5', NOW(), NOW() ),
('Ocampo','5', NOW(), NOW() ),
('Nadadores','5', NOW(), NOW() ),
('Sierra Mojada','5', NOW(), NOW() ),
('Cuatro Ciénegas','5', NOW(), NOW() ),
('Lamadrid','5', NOW(), NOW() ),
('Sacramento','5', NOW(), NOW() ),
('San Pedro','5', NOW(), NOW() ),
('Francisco I. Madero','5', NOW(), NOW() ),
('Parras','5', NOW(), NOW() ),
('Mexicali','2', NOW(), NOW() ),
('Tecate','2', NOW(), NOW() ),
('Tijuana','2', NOW(), NOW() ),
('Playas de Rosarito','2', NOW(), NOW() ),
('Ensenada','2', NOW(), NOW() ),
('Chihuahua','8', NOW(), NOW() ),
('Cuauhtémoc','8', NOW(), NOW() ),
('Riva Palacio','8', NOW(), NOW() ),
('Aquiles Serdán','8', NOW(), NOW() ),
('Bachíniva','8', NOW(), NOW() ),
('Guerrero','8', NOW(), NOW() ),
('Nuevo Casas Grandes','8', NOW(), NOW() ),
('Ascensión','8', NOW(), NOW() ),
('Janos','8', NOW(), NOW() ),
('Casas Grandes','8', NOW(), NOW() ),
('Galeana','8', NOW(), NOW() ),
('Buenaventura','8', NOW(), NOW() ),
('Gómez Farías','8', NOW(), NOW() ),
('Ignacio Zaragoza','8', NOW(), NOW() ),
('Madera','8', NOW(), NOW() ),
('Namiquipa','8', NOW(), NOW() ),
('Temósachic','8', NOW(), NOW() ),
('Matachí','8', NOW(), NOW() ),
('Juárez','8', NOW(), NOW() ),
('Guadalupe','8', NOW(), NOW() ),
('Praxedis G. Guerrero','8', NOW(), NOW() ),
('Ahumada','8', NOW(), NOW() ),
('Coyame del Sotol','8', NOW(), NOW() ),
('Ojinaga','8', NOW(), NOW() ),
('Aldama','8', NOW(), NOW() ),
('Julimes','8', NOW(), NOW() ),
('Manuel Benavides','8', NOW(), NOW() ),
('Delicias','8', NOW(), NOW() ),
('Rosales','8', NOW(), NOW() ),
('Meoqui','8', NOW(), NOW() ),
('Dr. Belisario Domínguez','8', NOW(), NOW() ),
('Satevó','8', NOW(), NOW() ),
('San Francisco de Borja','8', NOW(), NOW() ),
('Nonoava','8', NOW(), NOW() ),
('Guachochi','8', NOW(), NOW() ),
('Bocoyna','8', NOW(), NOW() ),
('Cusihuiriachi','8', NOW(), NOW() ),
('Gran Morelos','8', NOW(), NOW() ),
('Santa Isabel','8', NOW(), NOW() ),
('Carichí','8', NOW(), NOW() ),
('Uruachi','8', NOW(), NOW() ),
('Ocampo','8', NOW(), NOW() ),
('Moris','8', NOW(), NOW() ),
('Chínipas','8', NOW(), NOW() ),
('Maguarichi','8', NOW(), NOW() ),
('Guazapares','8', NOW(), NOW() ),
('Batopilas','8', NOW(), NOW() ),
('Urique','8', NOW(), NOW() ),
('Morelos','8', NOW(), NOW() ),
('Guadalupe y Calvo','8', NOW(), NOW() ),
('San Francisco del Oro','8', NOW(), NOW() ),
('Rosario','8', NOW(), NOW() ),
('Huejotitán','8', NOW(), NOW() ),
('El Tule','8', NOW(), NOW() ),
('Balleza','8', NOW(), NOW() ),
('Santa Bárbara','8', NOW(), NOW() ),
('Camargo','8', NOW(), NOW() ),
('Saucillo','8', NOW(), NOW() ),
('Valle de Zaragoza','8', NOW(), NOW() ),
('La Cruz','8', NOW(), NOW() ),
('San Francisco de Conchos','8', NOW(), NOW() ),
('Hidalgo del Parral','8', NOW(), NOW() ),
('Allende','8', NOW(), NOW() ),
('López','8', NOW(), NOW() ),
('Matamoros','8', NOW(), NOW() ),
('Jiménez','8', NOW(), NOW() ),
('Coronado','8', NOW(), NOW() ),
('Puebla','21', NOW(), NOW() ),
('Tlaltenango','21', NOW(), NOW() ),
('San Miguel Xoxtla','21', NOW(), NOW() ),
('Juan C. Bonilla','21', NOW(), NOW() ),
('Coronango','21', NOW(), NOW() ),
('Cuautlancingo','21', NOW(), NOW() ),
('San Pedro Cholula','21', NOW(), NOW() ),
('San Andrés Cholula','21', NOW(), NOW() ),
('Ocoyucan','21', NOW(), NOW() ),
('Amozoc','21', NOW(), NOW() ),
('Francisco Z. Mena','21', NOW(), NOW() ),
('Pantepec','21', NOW(), NOW() ),
('Venustiano Carranza','21', NOW(), NOW() ),
('Jalpan','21', NOW(), NOW() ),
('Tlaxco','21', NOW(), NOW() ),
('Tlacuilotepec','21', NOW(), NOW() ),
('Xicotepec','21', NOW(), NOW() ),
('Pahuatlán','21', NOW(), NOW() ),
('Honey','21', NOW(), NOW() ),
('Naupan','21', NOW(), NOW() ),
('Huauchinango','21', NOW(), NOW() ),
('Ahuazotepec','21', NOW(), NOW() ),
('Juan Galindo','21', NOW(), NOW() ),
('Tlaola','21', NOW(), NOW() ),
('Zihuateutla','21', NOW(), NOW() ),
('Jopala','21', NOW(), NOW() ),
('Tlapacoya','21', NOW(), NOW() ),
('Chignahuapan','21', NOW(), NOW() ),
('Zacatlán','21', NOW(), NOW() ),
('Chiconcuautla','21', NOW(), NOW() ),
('Ahuacatlán','21', NOW(), NOW() ),
('Tepetzintla','21', NOW(), NOW() ),
('San Felipe Tepatlán','21', NOW(), NOW() ),
('Amixtlán','21', NOW(), NOW() ),
('Tepango de Rodríguez','21', NOW(), NOW() ),
('Zongozotla','21', NOW(), NOW() ),
('Hermenegildo Galeana','21', NOW(), NOW() ),
('Olintla','21', NOW(), NOW() ),
('Coatepec','21', NOW(), NOW() ),
('Camocuautla','21', NOW(), NOW() ),
('Hueytlalpan','21', NOW(), NOW() ),
('Zapotitlán de Méndez','21', NOW(), NOW() ),
('Huitzilan de Serdán','21', NOW(), NOW() ),
('Xochitlán de Vicente Suárez','21', NOW(), NOW() ),
('Huehuetla','21', NOW(), NOW() ),
('Ixtepec','21', NOW(), NOW() ),
('Atlequizayan','21', NOW(), NOW() ),
('Tenampulco','21', NOW(), NOW() ),
('Tuzamapan de Galeana','21', NOW(), NOW() ),
('Caxhuacan','21', NOW(), NOW() ),
('Jonotla','21', NOW(), NOW() ),
('Zoquiapan','21', NOW(), NOW() ),
('Nauzontla','21', NOW(), NOW() ),
('Cuetzalan del Progreso','21', NOW(), NOW() ),
('Ayotoxco de Guerrero','21', NOW(), NOW() ),
('Hueytamalco','21', NOW(), NOW() ),
('Acateno','21', NOW(), NOW() ),
('Cuautempan','21', NOW(), NOW() ),
('Aquixtla','21', NOW(), NOW() ),
('Tetela de Ocampo','21', NOW(), NOW() ),
('Xochiapulco','21', NOW(), NOW() ),
('Zacapoaxtla','21', NOW(), NOW() ),
('Zaragoza','21', NOW(), NOW() ),
('Ixtacamaxtitlán','21', NOW(), NOW() ),
('Zautla','21', NOW(), NOW() ),
('Ocotepec','21', NOW(), NOW() ),
('Libres','21', NOW(), NOW() ),
('Teziutlán','21', NOW(), NOW() ),
('Tlatlauquitepec','21', NOW(), NOW() ),
('Yaonáhuac','21', NOW(), NOW() ),
('Hueyapan','21', NOW(), NOW() ),
('Teteles de Avila Castillo','21', NOW(), NOW() ),
('Atempan','21', NOW(), NOW() ),
('Chignautla','21', NOW(), NOW() ),
('Xiutetelco','21', NOW(), NOW() ),
('Cuyoaco','21', NOW(), NOW() ),
('Tepeyahualco','21', NOW(), NOW() ),
('San Martín Texmelucan','21', NOW(), NOW() ),
('Tlahuapan','21', NOW(), NOW() ),
('San Matías Tlalancaleca','21', NOW(), NOW() ),
('San Salvador el Verde','21', NOW(), NOW() ),
('San Felipe Teotlalcingo','21', NOW(), NOW() ),
('Chiautzingo','21', NOW(), NOW() ),
('Huejotzingo','21', NOW(), NOW() ),
('Domingo Arenas','21', NOW(), NOW() ),
('Calpan','21', NOW(), NOW() ),
('San Nicolás de los Ranchos','21', NOW(), NOW() ),
('Atlixco','21', NOW(), NOW() ),
('Nealtican','21', NOW(), NOW() ),
('San Jerónimo Tecuanipan','21', NOW(), NOW() ),
('San Gregorio Atzompa','21', NOW(), NOW() ),
('Tochimilco','21', NOW(), NOW() ),
('Tianguismanalco','21', NOW(), NOW() ),
('Santa Isabel Cholula','21', NOW(), NOW() ),
('Huaquechula','21', NOW(), NOW() ),
('San Diego la Mesa Tochimiltzingo','21', NOW(), NOW() ),
('Tepeojuma','21', NOW(), NOW() ),
('Izúcar de Matamoros','21', NOW(), NOW() ),
('Atzitzihuacán','21', NOW(), NOW() ),
('Acteopan','21', NOW(), NOW() ),
('Cohuecan','21', NOW(), NOW() ),
('Tepemaxalco','21', NOW(), NOW() ),
('Tlapanalá','21', NOW(), NOW() ),
('Tepexco','21', NOW(), NOW() ),
('Tilapa','21', NOW(), NOW() ),
('Chietla','21', NOW(), NOW() ),
('Atzala','21', NOW(), NOW() ),
('Teopantlán','21', NOW(), NOW() ),
('San Martín Totoltepec','21', NOW(), NOW() ),
('Xochiltepec','21', NOW(), NOW() ),
('Epatlán','21', NOW(), NOW() ),
('Ahuatlán','21', NOW(), NOW() ),
('Coatzingo','21', NOW(), NOW() ),
('Santa Catarina Tlaltempan','21', NOW(), NOW() ),
('Chigmecatitlán','21', NOW(), NOW() ),
('Zacapala','21', NOW(), NOW() ),
('Tepexi de Rodríguez','21', NOW(), NOW() ),
('Teotlalco','21', NOW(), NOW() ),
('Jolalpan','21', NOW(), NOW() ),
('Huehuetlán el Chico','21', NOW(), NOW() ),
('Chiautla','21', NOW(), NOW() ),
('Cohetzala','21', NOW(), NOW() ),
('Xicotlán','21', NOW(), NOW() ),
('Chila de la Sal','21', NOW(), NOW() ),
('Ixcamilpa de Guerrero','21', NOW(), NOW() ),
('Albino Zertuche','21', NOW(), NOW() ),
('Tulcingo','21', NOW(), NOW() ),
('Tehuitzingo','21', NOW(), NOW() ),
('Cuayuca de Andrade','21', NOW(), NOW() ),
('Santa Inés Ahuatempan','21', NOW(), NOW() ),
('Axutla','21', NOW(), NOW() ),
('Chinantla','21', NOW(), NOW() ),
('Ahuehuetitla','21', NOW(), NOW() ),
('San Pablo Anicano','21', NOW(), NOW() ),
('Tecomatlán','21', NOW(), NOW() ),
('Piaxtla','21', NOW(), NOW() ),
('Guadalupe','21', NOW(), NOW() ),
('Ixcaquixtla','21', NOW(), NOW() ),
('Coyotepec','21', NOW(), NOW() ),
('Xayacatlán de Bravo','21', NOW(), NOW() ),
('Totoltepec de Guerrero','21', NOW(), NOW() ),
('Acatlán','21', NOW(), NOW() ),
('San Jerónimo Xayacatlán','21', NOW(), NOW() ),
('San Pedro Yeloixtlahuaca','21', NOW(), NOW() ),
('Petlalcingo','21', NOW(), NOW() ),
('San Miguel Ixitlán','21', NOW(), NOW() ),
('Chila','21', NOW(), NOW() ),
('Rafael Lara Grajales','21', NOW(), NOW() ),
('San José Chiapa','21', NOW(), NOW() ),
('Oriental','21', NOW(), NOW() ),
('San Nicolás Buenos Aires','21', NOW(), NOW() ),
('Guadalupe Victoria','21', NOW(), NOW() ),
('Tlachichuca','21', NOW(), NOW() ),
('Lafragua','21', NOW(), NOW() ),
('Chilchotla','21', NOW(), NOW() ),
('Quimixtlán','21', NOW(), NOW() ),
('Chichiquila','21', NOW(), NOW() ),
('Tepatlaxco de Hidalgo','21', NOW(), NOW() ),
('Acajete','21', NOW(), NOW() ),
('Nopalucan','21', NOW(), NOW() ),
('Mazapiltepec de Juárez','21', NOW(), NOW() ),
('Soltepec','21', NOW(), NOW() ),
('Acatzingo','21', NOW(), NOW() ),
('San Salvador el Seco','21', NOW(), NOW() ),
('General Felipe Ángeles','21', NOW(), NOW() ),
('Aljojuca','21', NOW(), NOW() ),
('San Juan Atenco','21', NOW(), NOW() ),
('Tepeaca','21', NOW(), NOW() ),
('Cuautinchán','21', NOW(), NOW() ),
('Tecali de Herrera','21', NOW(), NOW() ),
('Mixtla','21', NOW(), NOW() ),
('Santo Tomás Hueyotlipan','21', NOW(), NOW() ),
('Tzicatlacoyan','21', NOW(), NOW() ),
('Huehuetlán el Grande','21', NOW(), NOW() ),
('La Magdalena Tlatlauquitepec','21', NOW(), NOW() ),
('San Juan Atzompa','21', NOW(), NOW() ),
('Huatlatlauca','21', NOW(), NOW() ),
('Los Reyes de Juárez','21', NOW(), NOW() ),
('Cuapiaxtla de Madero','21', NOW(), NOW() ),
('San Salvador Huixcolotla','21', NOW(), NOW() ),
('Quecholac','21', NOW(), NOW() ),
('Tecamachalco','21', NOW(), NOW() ),
('Palmar de Bravo','21', NOW(), NOW() ),
('Chalchicomula de Sesma','21', NOW(), NOW() ),
('Atzitzintla','21', NOW(), NOW() ),
('Esperanza','21', NOW(), NOW() ),
('Cañada Morelos','21', NOW(), NOW() ),
('Tlanepantla','21', NOW(), NOW() ),
('Tochtepec','21', NOW(), NOW() ),
('Atoyatempan','21', NOW(), NOW() ),
('Tepeyahualco de Cuauhtémoc','21', NOW(), NOW() ),
('Huitziltepec','21', NOW(), NOW() ),
('Molcaxac','21', NOW(), NOW() ),
('Xochitlán Todos Santos','21', NOW(), NOW() ),
('Yehualtepec','21', NOW(), NOW() ),
('Tlacotepec de Benito Juárez','21', NOW(), NOW() ),
('Juan N. Méndez','21', NOW(), NOW() ),
('Tehuacán','21', NOW(), NOW() ),
('Tepanco de López','21', NOW(), NOW() ),
('Chapulco','21', NOW(), NOW() ),
('Santiago Miahuatlán','21', NOW(), NOW() ),
('Nicolás Bravo','21', NOW(), NOW() ),
('Atexcal','21', NOW(), NOW() ),
('San Antonio Cañada','21', NOW(), NOW() ),
('Zapotitlán','21', NOW(), NOW() ),
('San Gabriel Chilac','21', NOW(), NOW() ),
('Caltepec','21', NOW(), NOW() ),
('Vicente Guerrero','21', NOW(), NOW() ),
('Ajalpan','21', NOW(), NOW() ),
('Eloxochitlán','21', NOW(), NOW() ),
('Zoquitlán','21', NOW(), NOW() ),
('San Sebastián Tlacotepec','21', NOW(), NOW() ),
('Altepexi','21', NOW(), NOW() ),
('Zinacatepec','21', NOW(), NOW() ),
('San José Miahuatlán','21', NOW(), NOW() ),
('Coxcatlán','21', NOW(), NOW() ),
('Coyomeapan','21', NOW(), NOW() ),
('San Luis Potosí','24', NOW(), NOW() ),
('Soledad de Graciano Sánchez','24', NOW(), NOW() ),
('Cerro de San Pedro','24', NOW(), NOW() ),
('Ahualulco','24', NOW(), NOW() ),
('Mexquitic de Carmona','24', NOW(), NOW() ),
('Villa de Arriaga','24', NOW(), NOW() ),
('Vanegas','24', NOW(), NOW() ),
('Cedral','24', NOW(), NOW() ),
('Catorce','24', NOW(), NOW() ),
('Charcas','24', NOW(), NOW() ),
('Salinas','24', NOW(), NOW() ),
('Santo Domingo','24', NOW(), NOW() ),
('Villa de Ramos','24', NOW(), NOW() ),
('Matehuala','24', NOW(), NOW() ),
('Villa de la Paz','24', NOW(), NOW() ),
('Villa de Guadalupe','24', NOW(), NOW() ),
('Guadalcázar','24', NOW(), NOW() ),
('Moctezuma','24', NOW(), NOW() ),
('Venado','24', NOW(), NOW() ),
('Villa de Arista','24', NOW(), NOW() ),
('Villa Hidalgo','24', NOW(), NOW() ),
('Armadillo de los Infante','24', NOW(), NOW() ),
('Ciudad Valles','24', NOW(), NOW() ),
('Ebano','24', NOW(), NOW() ),
('Tamuín','24', NOW(), NOW() ),
('Ciudad del Maíz','24', NOW(), NOW() ),
('El Naranjo','24', NOW(), NOW() ),
('Alaquines','24', NOW(), NOW() ),
('Cárdenas','24', NOW(), NOW() ),
('Cerritos','24', NOW(), NOW() ),
('Villa Juárez','24', NOW(), NOW() ),
('San Nicolás Tolentino','24', NOW(), NOW() ),
('Villa de Reyes','24', NOW(), NOW() ),
('Zaragoza','24', NOW(), NOW() ),
('Santa María del Río','24', NOW(), NOW() ),
('Tierra Nueva','24', NOW(), NOW() ),
('Rioverde','24', NOW(), NOW() ),
('Ciudad Fernández','24', NOW(), NOW() ),
('San Ciro de Acosta','24', NOW(), NOW() ),
('Tamasopo','24', NOW(), NOW() ),
('Rayón','24', NOW(), NOW() ),
('Aquismón','24', NOW(), NOW() ),
('Lagunillas','24', NOW(), NOW() ),
('Santa Catarina','24', NOW(), NOW() ),
('Tancanhuitz','24', NOW(), NOW() ),
('Tanlajás','24', NOW(), NOW() ),
('San Vicente Tancuayalab','24', NOW(), NOW() ),
('San Antonio','24', NOW(), NOW() ),
('Tanquián de Escobedo','24', NOW(), NOW() ),
('Tampamolón Corona','24', NOW(), NOW() ),
('Coxcatlán','24', NOW(), NOW() ),
('Huehuetlán','24', NOW(), NOW() ),
('Xilitla','24', NOW(), NOW() ),
('Axtla de Terrazas','24', NOW(), NOW() ),
('Tampacán','24', NOW(), NOW() ),
('San Martín Chalchicuautla','24', NOW(), NOW() ),
('Tamazunchale','24', NOW(), NOW() ),
('Matlapa','24', NOW(), NOW() ),
('Victoria','28', NOW(), NOW() ),
('Llera','28', NOW(), NOW() ),
('Güémez','28', NOW(), NOW() ),
('Casas','28', NOW(), NOW() ),
('Matamoros','28', NOW(), NOW() ),
('Valle Hermoso','28', NOW(), NOW() ),
('San Fernando','28', NOW(), NOW() ),
('Cruillas','28', NOW(), NOW() ),
('San Nicolás','28', NOW(), NOW() ),
('Soto la Marina','28', NOW(), NOW() ),
('Jiménez','28', NOW(), NOW() ),
('San Carlos','28', NOW(), NOW() ),
('Abasolo','28', NOW(), NOW() ),
('Padilla','28', NOW(), NOW() ),
('Hidalgo','28', NOW(), NOW() ),
('Mainero','28', NOW(), NOW() ),
('Villagrán','28', NOW(), NOW() ),
('Tula','28', NOW(), NOW() ),
('Jaumave','28', NOW(), NOW() ),
('Miquihuana','28', NOW(), NOW() ),
('Bustamante','28', NOW(), NOW() ),
('Palmillas','28', NOW(), NOW() ),
('Ocampo','28', NOW(), NOW() ),
('Nuevo Laredo','28', NOW(), NOW() ),
('Miguel Alemán','28', NOW(), NOW() ),
('Guerrero','28', NOW(), NOW() ),
('Mier','28', NOW(), NOW() ),
('Gustavo Díaz Ordaz','28', NOW(), NOW() ),
('Camargo','28', NOW(), NOW() ),
('Reynosa','28', NOW(), NOW() ),
('Río Bravo','28', NOW(), NOW() ),
('Méndez','28', NOW(), NOW() ),
('Burgos','28', NOW(), NOW() ),
('Tampico','28', NOW(), NOW() ),
('Ciudad Madero','28', NOW(), NOW() ),
('Altamira','28', NOW(), NOW() ),
('Aldama','28', NOW(), NOW() ),
('González','28', NOW(), NOW() ),
('Xicoténcatl','28', NOW(), NOW() ),
('Gómez Farías','28', NOW(), NOW() ),
('El Mante','28', NOW(), NOW() ),
('Antiguo Morelos','28', NOW(), NOW() ),
('Nuevo Morelos','28', NOW(), NOW() ),
('Pachuca de Soto','13', NOW(), NOW() ),
('Mineral del Chico','13', NOW(), NOW() ),
('Mineral del Monte','13', NOW(), NOW() ),
('Ajacuba','13', NOW(), NOW() ),
('San Agustín Tlaxiaca','13', NOW(), NOW() ),
('Mineral de la Reforma','13', NOW(), NOW() ),
('Zapotlán de Juárez','13', NOW(), NOW() ),
('Jacala de Ledezma','13', NOW(), NOW() ),
('Pisaflores','13', NOW(), NOW() ),
('Pacula','13', NOW(), NOW() ),
('La Misión','13', NOW(), NOW() ),
('Chapulhuacán','13', NOW(), NOW() ),
('Ixmiquilpan','13', NOW(), NOW() ),
('Zimapán','13', NOW(), NOW() ),
('Nicolás Flores','13', NOW(), NOW() ),
('Cardonal','13', NOW(), NOW() ),
('Tasquillo','13', NOW(), NOW() ),
('Alfajayucan','13', NOW(), NOW() ),
('Huichapan','13', NOW(), NOW() ),
('Tecozautla','13', NOW(), NOW() ),
('Nopala de Villagrán','13', NOW(), NOW() ),
('Actopan','13', NOW(), NOW() ),
('Santiago de Anaya','13', NOW(), NOW() ),
('San Salvador','13', NOW(), NOW() ),
('Francisco I. Madero','13', NOW(), NOW() ),
('El Arenal','13', NOW(), NOW() ),
('Mixquiahuala de Juárez','13', NOW(), NOW() ),
('Progreso de Obregón','13', NOW(), NOW() ),
('Chilcuautla','13', NOW(), NOW() ),
('Tezontepec de Aldama','13', NOW(), NOW() ),
('Tlahuelilpan','13', NOW(), NOW() ),
('Tula de Allende','13', NOW(), NOW() ),
('Tepeji del Río de Ocampo','13', NOW(), NOW() ),
('Chapantongo','13', NOW(), NOW() ),
('Tepetitlán','13', NOW(), NOW() ),
('Tetepango','13', NOW(), NOW() ),
('Tlaxcoapan','13', NOW(), NOW() ),
('Atitalaquia','13', NOW(), NOW() ),
('Atotonilco de Tula','13', NOW(), NOW() ),
('Huejutla de Reyes','13', NOW(), NOW() ),
('San Felipe Orizatlán','13', NOW(), NOW() ),
('Jaltocán','13', NOW(), NOW() ),
('Huautla','13', NOW(), NOW() ),
('Atlapexco','13', NOW(), NOW() ),
('Huazalingo','13', NOW(), NOW() ),
('Yahualica','13', NOW(), NOW() ),
('Xochiatipan','13', NOW(), NOW() ),
('Molango de Escamilla','13', NOW(), NOW() ),
('Tepehuacán de Guerrero','13', NOW(), NOW() ),
('Lolotla','13', NOW(), NOW() ),
('Tlanchinol','13', NOW(), NOW() ),
('Tlahuiltepa','13', NOW(), NOW() ),
('Juárez Hidalgo','13', NOW(), NOW() ),
('Zacualtipán de Ángeles','13', NOW(), NOW() ),
('Calnali','13', NOW(), NOW() ),
('Xochicoatlán','13', NOW(), NOW() ),
('Tianguistengo','13', NOW(), NOW() ),
('Atotonilco el Grande','13', NOW(), NOW() ),
('Eloxochitlán','13', NOW(), NOW() ),
('Metztitlán','13', NOW(), NOW() ),
('San Agustín Metzquititlán','13', NOW(), NOW() ),
('Metepec','13', NOW(), NOW() ),
('Huehuetla','13', NOW(), NOW() ),
('San Bartolo Tutotepec','13', NOW(), NOW() ),
('Agua Blanca de Iturbide','13', NOW(), NOW() ),
('Tenango de Doria','13', NOW(), NOW() ),
('Huasca de Ocampo','13', NOW(), NOW() ),
('Acatlán','13', NOW(), NOW() ),
('Omitlán de Juárez','13', NOW(), NOW() ),
('Epazoyucan','13', NOW(), NOW() ),
('Tulancingo de Bravo','13', NOW(), NOW() ),
('Acaxochitlán','13', NOW(), NOW() ),
('Cuautepec de Hinojosa','13', NOW(), NOW() ),
('Santiago Tulantepec de Lugo Guerrero','13', NOW(), NOW() ),
('Singuilucan','13', NOW(), NOW() ),
('Tizayuca','13', NOW(), NOW() ),
('Zempoala','13', NOW(), NOW() ),
('Tolcayuca','13', NOW(), NOW() ),
('Villa de Tezontepec','13', NOW(), NOW() ),
('Apan','13', NOW(), NOW() ),
('Tlanalapa','13', NOW(), NOW() ),
('Almoloya','13', NOW(), NOW() ),
('Emiliano Zapata','13', NOW(), NOW() ),
('Tepeapulco','13', NOW(), NOW() ),
('La Paz','3', NOW(), NOW() ),
('Los Cabos','3', NOW(), NOW() ),
('Comondú','3', NOW(), NOW() ),
('Loreto','3', NOW(), NOW() ),
('Mulegé','3', NOW(), NOW() ),
('Chilpancingo de los Bravo','12', NOW(), NOW() ),
('General Heliodoro Castillo','12', NOW(), NOW() ),
('Leonardo Bravo','12', NOW(), NOW() ),
('Tixtla de Guerrero','12', NOW(), NOW() ),
('Ayutla de los Libres','12', NOW(), NOW() ),
('Mochitlán','12', NOW(), NOW() ),
('Quechultenango','12', NOW(), NOW() ),
('Tecoanapa','12', NOW(), NOW() ),
('Acapulco de Juárez','12', NOW(), NOW() ),
('Juan R. Escudero','12', NOW(), NOW() ),
('San Marcos','12', NOW(), NOW() ),
('Iguala de la Independencia','12', NOW(), NOW() ),
('Huitzuco de los Figueroa','12', NOW(), NOW() ),
('Tepecoacuilco de Trujano','12', NOW(), NOW() ),
('Eduardo Neri','12', NOW(), NOW() ),
('Taxco de Alarcón','12', NOW(), NOW() ),
('Buenavista de Cuéllar','12', NOW(), NOW() ),
('Tetipac','12', NOW(), NOW() ),
('Pilcaya','12', NOW(), NOW() ),
('Teloloapan','12', NOW(), NOW() ),
('Ixcateopan de Cuauhtémoc','12', NOW(), NOW() ),
('Pedro Ascencio Alquisiras','12', NOW(), NOW() ),
('General Canuto A. Neri','12', NOW(), NOW() ),
('Arcelia','12', NOW(), NOW() ),
('Apaxtla','12', NOW(), NOW() ),
('Cuetzala del Progreso','12', NOW(), NOW() ),
('Cocula','12', NOW(), NOW() ),
('Tlapehuala','12', NOW(), NOW() ),
('Cutzamala de Pinzón','12', NOW(), NOW() ),
('Pungarabato','12', NOW(), NOW() ),
('Tlalchapa','12', NOW(), NOW() ),
('Coyuca de Catalán','12', NOW(), NOW() ),
('Ajuchitlán del Progreso','12', NOW(), NOW() ),
('Zirándaro','12', NOW(), NOW() ),
('San Miguel Totolapan','12', NOW(), NOW() ),
('La Unión de Isidoro Montes de Oca','12', NOW(), NOW() ),
('Petatlán','12', NOW(), NOW() ),
('Coahuayutla de José María Izazaga','12', NOW(), NOW() ),
('Zihuatanejo de Azueta','12', NOW(), NOW() ),
('Técpan de Galeana','12', NOW(), NOW() ),
('Atoyac de Álvarez','12', NOW(), NOW() ),
('Benito Juárez','12', NOW(), NOW() ),
('Coyuca de Benítez','12', NOW(), NOW() ),
('Olinalá','12', NOW(), NOW() ),
('Atenango del Río','12', NOW(), NOW() ),
('Copalillo','12', NOW(), NOW() ),
('Cualác','12', NOW(), NOW() ),
('Chilapa de Álvarez','12', NOW(), NOW() ),
('José Joaquín de Herrera','12', NOW(), NOW() ),
('Ahuacuotzingo','12', NOW(), NOW() ),
('Zitlala','12', NOW(), NOW() ),
('Mártir de Cuilapan','12', NOW(), NOW() ),
('Huamuxtitlán','12', NOW(), NOW() ),
('Xochihuehuetlán','12', NOW(), NOW() ),
('Alpoyeca','12', NOW(), NOW() ),
('Tlapa de Comonfort','12', NOW(), NOW() ),
('Tlalixtaquilla de Maldonado','12', NOW(), NOW() ),
('Xalpatláhuac','12', NOW(), NOW() ),
('Zapotitlán Tablas','12', NOW(), NOW() ),
('Acatepec','12', NOW(), NOW() ),
('Atlixtac','12', NOW(), NOW() ),
('Copanatoyac','12', NOW(), NOW() ),
('Malinaltepec','12', NOW(), NOW() ),
('Iliatenco','12', NOW(), NOW() ),
('Tlacoapa','12', NOW(), NOW() ),
('Atlamajalcingo del Monte','12', NOW(), NOW() ),
('San Luis Acatlán','12', NOW(), NOW() ),
('Metlatónoc','12', NOW(), NOW() ),
('Cochoapa el Grande','12', NOW(), NOW() ),
('Alcozauca de Guerrero','12', NOW(), NOW() ),
('Ometepec','12', NOW(), NOW() ),
('Tlacoachistlahuaca','12', NOW(), NOW() ),
('Xochistlahuaca','12', NOW(), NOW() ),
('Florencio Villarreal','12', NOW(), NOW() ),
('Cuautepec','12', NOW(), NOW() ),
('Copala','12', NOW(), NOW() ),
('Azoyú','12', NOW(), NOW() ),
('Juchitán','12', NOW(), NOW() ),
('Marquelia','12', NOW(), NOW() ),
('Cuajinicuilapa','12', NOW(), NOW() ),
('Igualapa','12', NOW(), NOW() ),
('Mérida','31', NOW(), NOW() ),
('Progreso','31', NOW(), NOW() ),
('Chicxulub Pueblo','31', NOW(), NOW() ),
('Ixil','31', NOW(), NOW() ),
('Conkal','31', NOW(), NOW() ),
('Yaxkukul','31', NOW(), NOW() ),
('Hunucmá','31', NOW(), NOW() ),
('Ucú','31', NOW(), NOW() ),
('Kinchil','31', NOW(), NOW() ),
('Tetiz','31', NOW(), NOW() ),
('Celestún','31', NOW(), NOW() ),
('Kanasín','31', NOW(), NOW() ),
('Timucuy','31', NOW(), NOW() ),
('Acanceh','31', NOW(), NOW() ),
('Tixpéhual','31', NOW(), NOW() ),
('Umán','31', NOW(), NOW() ),
('Telchac Pueblo','31', NOW(), NOW() ),
('Dzemul','31', NOW(), NOW() ),
('Telchac Puerto','31', NOW(), NOW() ),
('Cansahcab','31', NOW(), NOW() ),
('Sinanché','31', NOW(), NOW() ),
('Yobaín','31', NOW(), NOW() ),
('Motul','31', NOW(), NOW() ),
('Baca','31', NOW(), NOW() ),
('Mocochá','31', NOW(), NOW() ),
('Muxupip','31', NOW(), NOW() ),
('Cacalchén','31', NOW(), NOW() ),
('Bokobá','31', NOW(), NOW() ),
('Tixkokob','31', NOW(), NOW() ),
('Hoctún','31', NOW(), NOW() ),
('Tahmek','31', NOW(), NOW() ),
('Dzidzantún','31', NOW(), NOW() ),
('Temax','31', NOW(), NOW() ),
('Tekantó','31', NOW(), NOW() ),
('Teya','31', NOW(), NOW() ),
('Suma','31', NOW(), NOW() ),
('Tepakán','31', NOW(), NOW() ),
('Tekal de Venegas','31', NOW(), NOW() ),
('Izamal','31', NOW(), NOW() ),
('Hocabá','31', NOW(), NOW() ),
('Xocchel','31', NOW(), NOW() ),
('Seyé','31', NOW(), NOW() ),
('Cuzamá','31', NOW(), NOW() ),
('Homún','31', NOW(), NOW() ),
('Sanahcat','31', NOW(), NOW() ),
('Huhí','31', NOW(), NOW() ),
('Dzilam González','31', NOW(), NOW() ),
('Dzilam de Bravo','31', NOW(), NOW() ),
('Panabá','31', NOW(), NOW() ),
('San Felipe','31', NOW(), NOW() ),
('Buctzotz','31', NOW(), NOW() ),
('Sucilá','31', NOW(), NOW() ),
('Cenotillo','31', NOW(), NOW() ),
('Dzoncauich','31', NOW(), NOW() ),
('Tunkás','31', NOW(), NOW() ),
('Quintana Roo','31', NOW(), NOW() ),
('Dzitás','31', NOW(), NOW() ),
('Kantunil','31', NOW(), NOW() ),
('Sudzal','31', NOW(), NOW() ),
('Tekit','31', NOW(), NOW() ),
('Sotuta','31', NOW(), NOW() ),
('Tizimín','31', NOW(), NOW() ),
('Río Lagartos','31', NOW(), NOW() ),
('Espita','31', NOW(), NOW() ),
('Temozón','31', NOW(), NOW() ),
('Calotmul','31', NOW(), NOW() ),
('Tinum','31', NOW(), NOW() ),
('Chankom','31', NOW(), NOW() ),
('Chichimilá','31', NOW(), NOW() ),
('Tixcacalcupul','31', NOW(), NOW() ),
('Kaua','31', NOW(), NOW() ),
('Cuncunul','31', NOW(), NOW() ),
('Tekom','31', NOW(), NOW() ),
('Chemax','31', NOW(), NOW() ),
('Valladolid','31', NOW(), NOW() ),
('Uayma','31', NOW(), NOW() ),
('Maxcanú','31', NOW(), NOW() ),
('Samahil','31', NOW(), NOW() ),
('Opichén','31', NOW(), NOW() ),
('Chocholá','31', NOW(), NOW() ),
('Kopomá','31', NOW(), NOW() ),
('Tecoh','31', NOW(), NOW() ),
('Abalá','31', NOW(), NOW() ),
('Halachó','31', NOW(), NOW() ),
('Muna','31', NOW(), NOW() ),
('Sacalum','31', NOW(), NOW() ),
('Maní','31', NOW(), NOW() ),
('Dzán','31', NOW(), NOW() ),
('Chapab','31', NOW(), NOW() ),
('Ticul','31', NOW(), NOW() ),
('Oxkutzcab','31', NOW(), NOW() ),
('Santa Elena','31', NOW(), NOW() ),
('Mama','31', NOW(), NOW() ),
('Chumayel','31', NOW(), NOW() ),
('Mayapán','31', NOW(), NOW() ),
('Teabo','31', NOW(), NOW() ),
('Cantamayec','31', NOW(), NOW() ),
('Yaxcabá','31', NOW(), NOW() ),
('Peto','31', NOW(), NOW() ),
('Chikindzonot','31', NOW(), NOW() ),
('Tahdziú','31', NOW(), NOW() ),
('Tixmehuac','31', NOW(), NOW() ),
('Chacsinkín','31', NOW(), NOW() ),
('Tzucacab','31', NOW(), NOW() ),
('Tekax','31', NOW(), NOW() ),
('Akil','31', NOW(), NOW() ),
('Tlaxcala','29', NOW(), NOW() ),
('Ixtacuixtla de Mariano Matamoros','29', NOW(), NOW() ),
('Santa Ana Nopalucan','29', NOW(), NOW() ),
('Panotla','29', NOW(), NOW() ),
('Totolac','29', NOW(), NOW() ),
('Tepeyanco','29', NOW(), NOW() ),
('Santa Isabel Xiloxoxtla','29', NOW(), NOW() ),
('San Juan Huactzinco','29', NOW(), NOW() ),
('Calpulalpan','29', NOW(), NOW() ),
('Sanctórum de Lázaro Cárdenas','29', NOW(), NOW() ),
('Benito Juárez','29', NOW(), NOW() ),
('Hueyotlipan','29', NOW(), NOW() ),
('Tlaxco','29', NOW(), NOW() ),
('Nanacamilpa de Mariano Arista','29', NOW(), NOW() ),
('Españita','29', NOW(), NOW() ),
('Apizaco','29', NOW(), NOW() ),
('Atlangatepec','29', NOW(), NOW() ),
('Muñoz de Domingo Arenas','29', NOW(), NOW() ),
('Tetla de la Solidaridad','29', NOW(), NOW() ),
('Xaltocan','29', NOW(), NOW() ),
('San Lucas Tecopilco','29', NOW(), NOW() ),
('Yauhquemecan','29', NOW(), NOW() ),
('Xaloztoc','29', NOW(), NOW() ),
('Tocatlán','29', NOW(), NOW() ),
('Tzompantepec','29', NOW(), NOW() ),
('San José Teacalco','29', NOW(), NOW() ),
('Huamantla','29', NOW(), NOW() ),
('Terrenate','29', NOW(), NOW() ),
('Lázaro Cárdenas','29', NOW(), NOW() ),
('Emiliano Zapata','29', NOW(), NOW() ),
('Altzayanca','29', NOW(), NOW() ),
('Cuapiaxtla','29', NOW(), NOW() ),
('El Carmen Tequexquitla','29', NOW(), NOW() ),
('Ixtenco','29', NOW(), NOW() ),
('Zitlaltepec de Trinidad Sánchez Santos','29', NOW(), NOW() ),
('Apetatitlán de Antonio Carvajal','29', NOW(), NOW() ),
('Amaxac de Guerrero','29', NOW(), NOW() ),
('Santa Cruz Tlaxcala','29', NOW(), NOW() ),
('Cuaxomulco','29', NOW(), NOW() ),
('Contla de Juan Cuamatzi','29', NOW(), NOW() ),
('Tepetitla de Lardizábal','29', NOW(), NOW() ),
('Natívitas','29', NOW(), NOW() ),
('Santa Apolonia Teacalco','29', NOW(), NOW() ),
('Tetlatlahuca','29', NOW(), NOW() ),
('San Damián Texoloc','29', NOW(), NOW() ),
('San Jerónimo Zacualpan','29', NOW(), NOW() ),
('Zacatelco','29', NOW(), NOW() ),
('San Lorenzo Axocomanitla','29', NOW(), NOW() ),
('Santa Catarina Ayometla','29', NOW(), NOW() ),
('Xicohtzinco','29', NOW(), NOW() ),
('Papalotla de Xicohténcatl','29', NOW(), NOW() ),
('Chiautempan','29', NOW(), NOW() ),
('La Magdalena Tlaltelulco','29', NOW(), NOW() ),
('San Francisco Tetlanohcan','29', NOW(), NOW() ),
('Teolocholco','29', NOW(), NOW() ),
('Acuamanala de Miguel Hidalgo','29', NOW(), NOW() ),
('Santa Cruz Quilehtla','29', NOW(), NOW() ),
('Mazatecochco de José María Morelos','29', NOW(), NOW() ),
('Tenancingo','29', NOW(), NOW() ),
('San Pablo del Monte','29', NOW(), NOW() ),
('Colima','6', NOW(), NOW() ),
('Tecomán','6', NOW(), NOW() ),
('Manzanillo','6', NOW(), NOW() ),
('Armería','6', NOW(), NOW() ),
('Coquimatlán','6', NOW(), NOW() ),
('Comala','6', NOW(), NOW() ),
('Cuauhtémoc','6', NOW(), NOW() ),
('Ixtlahuacán','6', NOW(), NOW() ),
('Minatitlán','6', NOW(), NOW() ),
('Villa de Álvarez','6', NOW(), NOW() ),
('Oaxaca de Juárez','20', NOW(), NOW() ),
('Villa de Etla','20', NOW(), NOW() ),
('San Juan Bautista Atatlahuca','20', NOW(), NOW() ),
('San Jerónimo Sosola','20', NOW(), NOW() ),
('San Juan Bautista Jayacatlán','20', NOW(), NOW() ),
('San Francisco Telixtlahuaca','20', NOW(), NOW() ),
('Santiago Tenango','20', NOW(), NOW() ),
('San Pablo Huitzo','20', NOW(), NOW() ),
('San Juan del Estado','20', NOW(), NOW() ),
('Magdalena Apasco','20', NOW(), NOW() ),
('Santiago Suchilquitongo','20', NOW(), NOW() ),
('San Juan Bautista Guelache','20', NOW(), NOW() ),
('Reyes Etla','20', NOW(), NOW() ),
('Nazareno Etla','20', NOW(), NOW() ),
('San Andrés Zautla','20', NOW(), NOW() ),
('San Agustín Etla','20', NOW(), NOW() ),
('Soledad Etla','20', NOW(), NOW() ),
('Santo Tomás Mazaltepec','20', NOW(), NOW() ),
('Guadalupe Etla','20', NOW(), NOW() ),
('San Pablo Etla','20', NOW(), NOW() ),
('San Felipe Tejalápam','20', NOW(), NOW() ),
('San Lorenzo Cacaotepec','20', NOW(), NOW() ),
('Santa María Peñoles','20', NOW(), NOW() ),
('Santiago Tlazoyaltepec','20', NOW(), NOW() ),
('Tlalixtac de Cabrera','20', NOW(), NOW() ),
('San Jacinto Amilpas','20', NOW(), NOW() ),
('San Andrés Huayápam','20', NOW(), NOW() ),
('San Agustín Yatareni','20', NOW(), NOW() ),
('Santo Domingo Tomaltepec','20', NOW(), NOW() ),
('Santa María del Tule','20', NOW(), NOW() ),
('San Juan Bautista Tuxtepec','20', NOW(), NOW() ),
('Loma Bonita','20', NOW(), NOW() ),
('San José Independencia','20', NOW(), NOW() ),
('Cosolapa','20', NOW(), NOW() ),
('Acatlán de Pérez Figueroa','20', NOW(), NOW() ),
('San Miguel Soyaltepec','20', NOW(), NOW() ),
('Ayotzintepec','20', NOW(), NOW() ),
('San Pedro Ixcatlán','20', NOW(), NOW() ),
('San José Chiltepec','20', NOW(), NOW() ),
('San Felipe Jalapa de Díaz','20', NOW(), NOW() ),
('Santa María Jacatepec','20', NOW(), NOW() ),
('San Lucas Ojitlán','20', NOW(), NOW() ),
('San Juan Bautista Valle Nacional','20', NOW(), NOW() ),
('San Felipe Usila','20', NOW(), NOW() ),
('Huautla de Jiménez','20', NOW(), NOW() ),
('Santa María Chilchotla','20', NOW(), NOW() ),
('Santa Ana Ateixtlahuaca','20', NOW(), NOW() ),
('San Lorenzo Cuaunecuiltitla','20', NOW(), NOW() ),
('San Francisco Huehuetlán','20', NOW(), NOW() ),
('San Pedro Ocopetatillo','20', NOW(), NOW() ),
('Santa Cruz Acatepec','20', NOW(), NOW() ),
('Eloxochitlán de Flores Magón','20', NOW(), NOW() ),
('Santiago Texcalcingo','20', NOW(), NOW() ),
('Teotitlán de Flores Magón','20', NOW(), NOW() ),
('Santa María Teopoxco','20', NOW(), NOW() ),
('San Martín Toxpalan','20', NOW(), NOW() ),
('San Jerónimo Tecóatl','20', NOW(), NOW() ),
('Santa María la Asunción','20', NOW(), NOW() ),
('Huautepec','20', NOW(), NOW() ),
('San Juan Coatzóspam','20', NOW(), NOW() ),
('San Lucas Zoquiápam','20', NOW(), NOW() ),
('San Antonio Nanahuatípam','20', NOW(), NOW() ),
('San José Tenango','20', NOW(), NOW() ),
('San Mateo Yoloxochitlán','20', NOW(), NOW() ),
('San Bartolomé Ayautla','20', NOW(), NOW() ),
('Mazatlán Villa de Flores','20', NOW(), NOW() ),
('San Juan de los Cués','20', NOW(), NOW() ),
('Santa María Tecomavaca','20', NOW(), NOW() ),
('Santa María Ixcatlán','20', NOW(), NOW() ),
('San Juan Bautista Cuicatlán','20', NOW(), NOW() ),
('Cuyamecalco Villa de Zaragoza','20', NOW(), NOW() ),
('Santa Ana Cuauhtémoc','20', NOW(), NOW() ),
('Chiquihuitlán de Benito Juárez','20', NOW(), NOW() ),
('San Pedro Teutila','20', NOW(), NOW() ),
('San Miguel Santa Flor','20', NOW(), NOW() ),
('Santa María Tlalixtac','20', NOW(), NOW() ),
('San Andrés Teotilálpam','20', NOW(), NOW() ),
('San Francisco Chapulapa','20', NOW(), NOW() ),
('Concepción Pápalo','20', NOW(), NOW() ),
('Santos Reyes Pápalo','20', NOW(), NOW() ),
('San Juan Bautista Tlacoatzintepec','20', NOW(), NOW() ),
('Santa María Pápalo','20', NOW(), NOW() ),
('San Juan Tepeuxila','20', NOW(), NOW() ),
('San Pedro Sochiápam','20', NOW(), NOW() ),
('Valerio Trujano','20', NOW(), NOW() ),
('San Pedro Jocotipac','20', NOW(), NOW() ),
('Santa María Texcatitlán','20', NOW(), NOW() ),
('San Pedro Jaltepetongo','20', NOW(), NOW() ),
('Santiago Nacaltepec','20', NOW(), NOW() ),
('Natividad','20', NOW(), NOW() ),
('San Juan Quiotepec','20', NOW(), NOW() ),
('San Pedro Yólox','20', NOW(), NOW() ),
('Santiago Comaltepec','20', NOW(), NOW() ),
('Abejones','20', NOW(), NOW() ),
('San Pablo Macuiltianguis','20', NOW(), NOW() ),
('Ixtlán de Juárez','20', NOW(), NOW() ),
('San Juan Atepec','20', NOW(), NOW() ),
('San Pedro Yaneri','20', NOW(), NOW() ),
('San Miguel Aloápam','20', NOW(), NOW() ),
('Teococuilco de Marcos Pérez','20', NOW(), NOW() ),
('Santa Ana Yareni','20', NOW(), NOW() ),
('San Juan Evangelista Analco','20', NOW(), NOW() ),
('Santa María Jaltianguis','20', NOW(), NOW() ),
('San Miguel del Río','20', NOW(), NOW() ),
('San Juan Chicomezúchil','20', NOW(), NOW() ),
('Capulálpam de Méndez','20', NOW(), NOW() ),
('Nuevo Zoquiápam','20', NOW(), NOW() ),
('Santiago Xiacuí','20', NOW(), NOW() ),
('Guelatao de Juárez','20', NOW(), NOW() ),
('Santa Catarina Ixtepeji','20', NOW(), NOW() ),
('San Miguel Yotao','20', NOW(), NOW() ),
('Santa Catarina Lachatao','20', NOW(), NOW() ),
('San Miguel Amatlán','20', NOW(), NOW() ),
('Santa María Yavesía','20', NOW(), NOW() ),
('Santiago Laxopa','20', NOW(), NOW() ),
('San Ildefonso Villa Alta','20', NOW(), NOW() ),
('Santiago Camotlán','20', NOW(), NOW() ),
('San Juan Yaeé','20', NOW(), NOW() ),
('Santiago Lalopa','20', NOW(), NOW() ),
('San Juan Yatzona','20', NOW(), NOW() ),
('Villa Talea de Castro','20', NOW(), NOW() ),
('Tanetze de Zaragoza','20', NOW(), NOW() ),
('San Juan Juquila Vijanos','20', NOW(), NOW() ),
('San Cristóbal Lachirioag','20', NOW(), NOW() ),
('Santa María Temaxcalapa','20', NOW(), NOW() ),
('Santo Domingo Roayaga','20', NOW(), NOW() ),
('Santa María Yalina','20', NOW(), NOW() ),
('San Andrés Solaga','20', NOW(), NOW() ),
('San Juan Tabaá','20', NOW(), NOW() ),
('San Melchor Betaza','20', NOW(), NOW() ),
('San Andrés Yaá','20', NOW(), NOW() ),
('San Bartolomé Zoogocho','20', NOW(), NOW() ),
('San Baltazar Yatzachi el Bajo','20', NOW(), NOW() ),
('Santiago Zoochila','20', NOW(), NOW() ),
('Villa Hidalgo','20', NOW(), NOW() ),
('San Francisco Cajonos','20', NOW(), NOW() ),
('San Mateo Cajonos','20', NOW(), NOW() ),
('San Pedro Cajonos','20', NOW(), NOW() ),
('Santo Domingo Xagacía','20', NOW(), NOW() ),
('San Pablo Yaganiza','20', NOW(), NOW() ),
('Santiago Choápam','20', NOW(), NOW() ),
('Santiago Jocotepec','20', NOW(), NOW() ),
('San Juan Lalana','20', NOW(), NOW() ),
('Santiago Yaveo','20', NOW(), NOW() ),
('San Juan Petlapa','20', NOW(), NOW() ),
('San Juan Comaltepec','20', NOW(), NOW() ),
('Heroica Ciudad de Huajuapan de León','20', NOW(), NOW() ),
('Santiago Chazumba','20', NOW(), NOW() ),
('Cosoltepec','20', NOW(), NOW() ),
('San Pedro y San Pablo Tequixtepec','20', NOW(), NOW() ),
('San Juan Bautista Suchitepec','20', NOW(), NOW() ),
('Santa Catarina Zapoquila','20', NOW(), NOW() ),
('Santiago Miltepec','20', NOW(), NOW() ),
('San Jerónimo Silacayoapilla','20', NOW(), NOW() ),
('Zapotitlán Palmas','20', NOW(), NOW() ),
('San Andrés Dinicuiti','20', NOW(), NOW() ),
('Santiago Cacaloxtepec','20', NOW(), NOW() ),
('Asunción Cuyotepeji','20', NOW(), NOW() ),
('Santa María Camotlán','20', NOW(), NOW() ),
('Santiago Huajolotitlán','20', NOW(), NOW() ),
('Santiago Tamazola','20', NOW(), NOW() ),
('San Juan Cieneguilla','20', NOW(), NOW() ),
('Zapotitlán Lagunas','20', NOW(), NOW() ),
('San Juan Ihualtepec','20', NOW(), NOW() ),
('San Nicolás Hidalgo','20', NOW(), NOW() ),
('Guadalupe de Ramírez','20', NOW(), NOW() ),
('San Andrés Tepetlapa','20', NOW(), NOW() ),
('San Miguel Ahuehuetitlán','20', NOW(), NOW() ),
('San Mateo Nejápam','20', NOW(), NOW() ),
('San Juan Bautista Tlachichilco','20', NOW(), NOW() ),
('Tezoatlán de Segura y Luna','20', NOW(), NOW() ),
('Fresnillo de Trujano','20', NOW(), NOW() ),
('Santiago Ayuquililla','20', NOW(), NOW() ),
('San José Ayuquila','20', NOW(), NOW() ),
('San Martín Zacatepec','20', NOW(), NOW() ),
('San Miguel Amatitlán','20', NOW(), NOW() ),
('Mariscala de Juárez','20', NOW(), NOW() ),
('Santa Cruz Tacache de Mina','20', NOW(), NOW() ),
('San Simón Zahuatlán','20', NOW(), NOW() ),
('San Marcos Arteaga','20', NOW(), NOW() ),
('San Jorge Nuchita','20', NOW(), NOW() ),
('Santos Reyes Yucuná','20', NOW(), NOW() ),
('Santo Domingo Tonalá','20', NOW(), NOW() ),
('Santo Domingo Yodohino','20', NOW(), NOW() ),
('San Juan Bautista Coixtlahuaca','20', NOW(), NOW() ),
('Tepelmeme Villa de Morelos','20', NOW(), NOW() ),
('Concepción Buenavista','20', NOW(), NOW() ),
('Santiago Ihuitlán Plumas','20', NOW(), NOW() ),
('Tlacotepec Plumas','20', NOW(), NOW() ),
('San Francisco Teopan','20', NOW(), NOW() ),
('Santa Magdalena Jicotlán','20', NOW(), NOW() ),
('San Mateo Tlapiltepec','20', NOW(), NOW() ),
('San Miguel Tequixtepec','20', NOW(), NOW() ),
('San Miguel Tulancingo','20', NOW(), NOW() ),
('Santiago Tepetlapa','20', NOW(), NOW() ),
('San Cristóbal Suchixtlahuaca','20', NOW(), NOW() ),
('Santa María Nativitas','20', NOW(), NOW() ),
('Silacayoápam','20', NOW(), NOW() ),
('Santiago Yucuyachi','20', NOW(), NOW() ),
('San Lorenzo Victoria','20', NOW(), NOW() ),
('San Agustín Atenango','20', NOW(), NOW() ),
('Calihualá','20', NOW(), NOW() ),
('Santa Cruz de Bravo','20', NOW(), NOW() ),
('Ixpantepec Nieves','20', NOW(), NOW() ),
('San Francisco Tlapancingo','20', NOW(), NOW() ),
('Santiago del Río','20', NOW(), NOW() ),
('San Pedro y San Pablo Teposcolula','20', NOW(), NOW() ),
('La Trinidad Vista Hermosa','20', NOW(), NOW() ),
('Villa de Tamazulápam del Progreso','20', NOW(), NOW() ),
('San Pedro Nopala','20', NOW(), NOW() ),
('Teotongo','20', NOW(), NOW() ),
('San Antonio Acutla','20', NOW(), NOW() ),
('Villa Tejúpam de la Unión','20', NOW(), NOW() ),
('Santo Domingo Tonaltepec','20', NOW(), NOW() ),
('Villa de Chilapa de Díaz','20', NOW(), NOW() ),
('San Antonino Monte Verde','20', NOW(), NOW() ),
('San Andrés Lagunas','20', NOW(), NOW() ),
('San Pedro Yucunama','20', NOW(), NOW() ),
('San Juan Teposcolula','20', NOW(), NOW() ),
('San Bartolo Soyaltepec','20', NOW(), NOW() ),
('Santiago Yolomécatl','20', NOW(), NOW() ),
('San Sebastián Nicananduta','20', NOW(), NOW() ),
('Santo Domingo Tlatayápam','20', NOW(), NOW() ),
('Santa María Nduayaco','20', NOW(), NOW() ),
('San Vicente Nuñú','20', NOW(), NOW() ),
('San Pedro Topiltepec','20', NOW(), NOW() ),
('Santiago Nejapilla','20', NOW(), NOW() ),
('Asunción Nochixtlán','20', NOW(), NOW() ),
('San Miguel Huautla','20', NOW(), NOW() ),
('San Miguel Chicahua','20', NOW(), NOW() ),
('Santa María Apazco','20', NOW(), NOW() ),
('Santiago Apoala','20', NOW(), NOW() ),
('Santa María Chachoápam','20', NOW(), NOW() ),
('San Pedro Coxcaltepec Cántaros','20', NOW(), NOW() ),
('Santiago Huauclilla','20', NOW(), NOW() ),
('Santo Domingo Yanhuitlán','20', NOW(), NOW() ),
('San Andrés Sinaxtla','20', NOW(), NOW() ),
('San Juan Yucuita','20', NOW(), NOW() ),
('San Juan Sayultepec','20', NOW(), NOW() ),
('Santiago Tillo','20', NOW(), NOW() ),
('San Francisco Chindúa','20', NOW(), NOW() ),
('San Mateo Etlatongo','20', NOW(), NOW() ),
('Santa Inés de Zaragoza','20', NOW(), NOW() ),
('Santiago Juxtlahuaca','20', NOW(), NOW() ),
('San Miguel Tlacotepec','20', NOW(), NOW() ),
('San Sebastián Tecomaxtlahuaca','20', NOW(), NOW() ),
('Santos Reyes Tepejillo','20', NOW(), NOW() ),
('San Juan Mixtepec -Dto. 08 -','20', NOW(), NOW() ),
('San Martín Peras','20', NOW(), NOW() ),
('Coicoyán de las Flores','20', NOW(), NOW() ),
('Heroica Ciudad de Tlaxiaco','20', NOW(), NOW() ),
('San Juan Ñumí','20', NOW(), NOW() ),
('San Pedro Mártir Yucuxaco','20', NOW(), NOW() ),
('San Martín Huamelúlpam','20', NOW(), NOW() ),
('Santa Cruz Tayata','20', NOW(), NOW() ),
('Santiago Nundiche','20', NOW(), NOW() ),
('Santa María del Rosario','20', NOW(), NOW() ),
('San Juan Achiutla','20', NOW(), NOW() ),
('Santa Catarina Tayata','20', NOW(), NOW() ),
('San Cristóbal Amoltepec','20', NOW(), NOW() ),
('San Miguel Achiutla','20', NOW(), NOW() ),
('San Martín Itunyoso','20', NOW(), NOW() ),
('Magdalena Peñasco','20', NOW(), NOW() ),
('San Bartolomé Yucuañe','20', NOW(), NOW() ),
('Santa Cruz Nundaco','20', NOW(), NOW() ),
('San Agustín Tlacotepec','20', NOW(), NOW() ),
('Santo Tomás Ocotepec','20', NOW(), NOW() ),
('San Antonio Sinicahua','20', NOW(), NOW() ),
('San Mateo Peñasco','20', NOW(), NOW() ),
('Santa María Tataltepec','20', NOW(), NOW() ),
('San Pedro Molinos','20', NOW(), NOW() ),
('Santa María Yosoyúa','20', NOW(), NOW() ),
('San Juan Teita','20', NOW(), NOW() ),
('Magdalena Jaltepec','20', NOW(), NOW() ),
('Magdalena Yodocono de Porfirio Díaz','20', NOW(), NOW() ),
('San Miguel Tecomatlán','20', NOW(), NOW() ),
('Magdalena Zahuatlán','20', NOW(), NOW() ),
('San Francisco Nuxaño','20', NOW(), NOW() ),
('San Pedro Tidaá','20', NOW(), NOW() ),
('San Francisco Jaltepetongo','20', NOW(), NOW() ),
('Santiago Tilantongo','20', NOW(), NOW() ),
('San Juan Diuxi','20', NOW(), NOW() ),
('San Andrés Nuxiño','20', NOW(), NOW() ),
('San Juan Tamazola','20', NOW(), NOW() ),
('Santo Domingo Nuxaá','20', NOW(), NOW() ),
('Yutanduchi de Guerrero','20', NOW(), NOW() ),
('San Pedro Teozacoalco','20', NOW(), NOW() ),
('San Miguel Piedras','20', NOW(), NOW() ),
('San Mateo Sindihui','20', NOW(), NOW() ),
('Juchitán de Zaragoza','20', NOW(), NOW() ),
('Ciudad Ixtepec','20', NOW(), NOW() ),
('El Espinal','20', NOW(), NOW() ),
('Santo Domingo Ingenio','20', NOW(), NOW() ),
('Santa María Xadani','20', NOW(), NOW() ),
('Santiago Niltepec','20', NOW(), NOW() ),
('San Dionisio del Mar','20', NOW(), NOW() ),
('Asunción Ixtaltepec','20', NOW(), NOW() ),
('San Francisco del Mar','20', NOW(), NOW() ),
('Unión Hidalgo','20', NOW(), NOW() ),
('San Miguel Chimalapa','20', NOW(), NOW() ),
('Santo Domingo Zanatepec','20', NOW(), NOW() ),
('Reforma de Pineda','20', NOW(), NOW() ),
('San Francisco Ixhuatán','20', NOW(), NOW() ),
('San Pedro Tapanatepec','20', NOW(), NOW() ),
('Chahuites','20', NOW(), NOW() ),
('Santiago Zacatepec','20', NOW(), NOW() ),
('Santo Domingo Tepuxtepec','20', NOW(), NOW() ),
('San Juan Cotzocón','20', NOW(), NOW() ),
('San Juan Mazatlán','20', NOW(), NOW() ),
('Totontepec Villa de Morelos','20', NOW(), NOW() ),
('Mixistlán de la Reforma','20', NOW(), NOW() ),
('Santa María Tlahuitoltepec','20', NOW(), NOW() ),
('Santa María Alotepec','20', NOW(), NOW() ),
('Santiago Atitlán','20', NOW(), NOW() ),
('Tamazulápam del Espíritu Santo','20', NOW(), NOW() ),
('San Pedro y San Pablo Ayutla','20', NOW(), NOW() ),
('Santa María Tepantlali','20', NOW(), NOW() ),
('San Miguel Quetzaltepec','20', NOW(), NOW() ),
('Asunción Cacalotepec','20', NOW(), NOW() ),
('San Pedro Ocotepec','20', NOW(), NOW() ),
('San Lucas Camotlán','20', NOW(), NOW() ),
('Santiago Ixcuintepec','20', NOW(), NOW() ),
('Matías Romero Avendaño','20', NOW(), NOW() ),
('San Juan Guichicovi','20', NOW(), NOW() ),
('Santo Domingo Petapa','20', NOW(), NOW() ),
('Santa María Chimalapa','20', NOW(), NOW() ),
('Santa María Petapa','20', NOW(), NOW() ),
('El Barrio de la Soledad','20', NOW(), NOW() ),
('Tlacolula de Matamoros','20', NOW(), NOW() ),
('San Sebastián Abasolo','20', NOW(), NOW() ),
('Villa Díaz Ordaz','20', NOW(), NOW() ),
('Santa María Guelacé','20', NOW(), NOW() ),
('Teotitlán del Valle','20', NOW(), NOW() ),
('San Francisco Lachigoló','20', NOW(), NOW() ),
('San Sebastián Teitipac','20', NOW(), NOW() ),
('Santa Ana del Valle','20', NOW(), NOW() ),
('San Pablo Villa de Mitla','20', NOW(), NOW() ),
('Santiago Matatlán','20', NOW(), NOW() ),
('Santo Domingo Albarradas','20', NOW(), NOW() ),
('Rojas de Cuauhtémoc','20', NOW(), NOW() ),
('San Juan Teitipac','20', NOW(), NOW() ),
('Santa Cruz Papalutla','20', NOW(), NOW() ),
('Magdalena Teitipac','20', NOW(), NOW() ),
('San Jerónimo Tlacochahuaya','20', NOW(), NOW() ),
('San Juan Guelavía','20', NOW(), NOW() ),
('San Lucas Quiaviní','20', NOW(), NOW() ),
('San Juan del Río','20', NOW(), NOW() ),
('San Bartolomé Quialana','20', NOW(), NOW() ),
('San Lorenzo Albarradas','20', NOW(), NOW() ),
('San Pedro Totolapa','20', NOW(), NOW() ),
('San Pedro Quiatoni','20', NOW(), NOW() ),
('Santa María Zoquitlán','20', NOW(), NOW() ),
('San Dionisio Ocotepec','20', NOW(), NOW() ),
('San Carlos Yautepec','20', NOW(), NOW() ),
('San Juan Juquila Mixes','20', NOW(), NOW() ),
('Nejapa de Madero','20', NOW(), NOW() ),
('Santa Ana Tavela','20', NOW(), NOW() ),
('San Juan Lajarcia','20', NOW(), NOW() ),
('San Bartolo Yautepec','20', NOW(), NOW() ),
('Santa María Ecatepec','20', NOW(), NOW() ),
('Asunción Tlacolulita','20', NOW(), NOW() ),
('San Pedro Mártir Quiechapa','20', NOW(), NOW() ),
('Santa María Quiegolani','20', NOW(), NOW() ),
('Santa Catarina Quioquitani','20', NOW(), NOW() ),
('Santa Catalina Quierí','20', NOW(), NOW() ),
('Salina Cruz','20', NOW(), NOW() ),
('Santiago Lachiguiri','20', NOW(), NOW() ),
('Santa María Jalapa del Marqués','20', NOW(), NOW() ),
('Santa María Totolapilla','20', NOW(), NOW() ),
('Santiago Laollaga','20', NOW(), NOW() ),
('Guevea de Humboldt','20', NOW(), NOW() ),
('Santo Domingo Chihuitán','20', NOW(), NOW() ),
('Santa María Guienagati','20', NOW(), NOW() ),
('Magdalena Tequisistlán','20', NOW(), NOW() ),
('Magdalena Tlacotepec','20', NOW(), NOW() ),
('San Pedro Comitancillo','20', NOW(), NOW() ),
('Santa María Mixtequilla','20', NOW(), NOW() ),
('Santo Domingo Tehuantepec','20', NOW(), NOW() ),
('San Pedro Huamelula','20', NOW(), NOW() ),
('San Pedro Huilotepec','20', NOW(), NOW() ),
('San Mateo del Mar','20', NOW(), NOW() ),
('San Blas Atempa','20', NOW(), NOW() ),
('Santiago Astata','20', NOW(), NOW() ),
('San Miguel Tenango','20', NOW(), NOW() ),
('Miahuatlán de Porfirio Díaz','20', NOW(), NOW() ),
('San Nicolás','20', NOW(), NOW() ),
('San Simón Almolongas','20', NOW(), NOW() ),
('San Luis Amatlán','20', NOW(), NOW() ),
('San José Lachiguiri','20', NOW(), NOW() ),
('Sitio de Xitlapehua','20', NOW(), NOW() ),
('San Francisco Logueche','20', NOW(), NOW() ),
('Santa Ana','20', NOW(), NOW() ),
('Santa Cruz Xitla','20', NOW(), NOW() ),
('Monjas','20', NOW(), NOW() ),
('San Ildefonso Amatlán','20', NOW(), NOW() ),
('Santa Catarina Cuixtla','20', NOW(), NOW() ),
('San José del Peñasco','20', NOW(), NOW() ),
('San Cristóbal Amatlán','20', NOW(), NOW() ),
('San Juan Mixtepec -Dto. 26 -','20', NOW(), NOW() ),
('San Pedro Mixtepec -Dto. 26 -','20', NOW(), NOW() ),
('Santa Lucía Miahuatlán','20', NOW(), NOW() ),
('San Jerónimo Coatlán','20', NOW(), NOW() ),
('San Sebastián Coatlán','20', NOW(), NOW() ),
('San Pablo Coatlán','20', NOW(), NOW() ),
('San Mateo Río Hondo','20', NOW(), NOW() ),
('Santo Tomás Tamazulapan','20', NOW(), NOW() ),
('San Andrés Paxtlán','20', NOW(), NOW() ),
('Santa María Ozolotepec','20', NOW(), NOW() ),
('San Miguel Coatlán','20', NOW(), NOW() ),
('San Sebastián Río Hondo','20', NOW(), NOW() ),
('San Miguel Suchixtepec','20', NOW(), NOW() ),
('Santo Domingo Ozolotepec','20', NOW(), NOW() ),
('San Francisco Ozolotepec','20', NOW(), NOW() ),
('Santiago Xanica','20', NOW(), NOW() ),
('San Marcial Ozolotepec','20', NOW(), NOW() ),
('San Juan Ozolotepec','20', NOW(), NOW() ),
('San Pedro Pochutla','20', NOW(), NOW() ),
('Santo Domingo de Morelos','20', NOW(), NOW() ),
('Santa Catarina Loxicha','20', NOW(), NOW() ),
('San Agustín Loxicha','20', NOW(), NOW() ),
('San Baltazar Loxicha','20', NOW(), NOW() ),
('Santa María Colotepec','20', NOW(), NOW() ),
('San Bartolomé Loxicha','20', NOW(), NOW() ),
('Santa María Tonameca','20', NOW(), NOW() ),
('Candelaria Loxicha','20', NOW(), NOW() ),
('Pluma Hidalgo','20', NOW(), NOW() ),
('San Pedro el Alto','20', NOW(), NOW() ),
('San Mateo Piñas','20', NOW(), NOW() ),
('Santa María Huatulco','20', NOW(), NOW() ),
('San Miguel del Puerto','20', NOW(), NOW() ),
('Putla Villa de Guerrero','20', NOW(), NOW() ),
('Constancia del Rosario','20', NOW(), NOW() ),
('Mesones Hidalgo','20', NOW(), NOW() ),
('Santa María Zacatepec','20', NOW(), NOW() ),
('San Pedro Amuzgos','20', NOW(), NOW() ),
('La Reforma','20', NOW(), NOW() ),
('Santa María Ipalapa','20', NOW(), NOW() ),
('Chalcatongo de Hidalgo','20', NOW(), NOW() ),
('Santa María Yucuhiti','20', NOW(), NOW() ),
('San Esteban Atatlahuca','20', NOW(), NOW() ),
('Santa Catarina Ticuá','20', NOW(), NOW() ),
('Santiago Nuyoó','20', NOW(), NOW() ),
('Santa Catarina Yosonotú','20', NOW(), NOW() ),
('San Miguel el Grande','20', NOW(), NOW() ),
('Santo Domingo Ixcatlán','20', NOW(), NOW() ),
('San Pablo Tijaltepec','20', NOW(), NOW() ),
('Santa Cruz Tacahua','20', NOW(), NOW() ),
('Santa Lucía Monteverde','20', NOW(), NOW() ),
('San Andrés Cabecera Nueva','20', NOW(), NOW() ),
('Santa María Yolotepec','20', NOW(), NOW() ),
('Santiago Yosondúa','20', NOW(), NOW() ),
('Santa Cruz Itundujia','20', NOW(), NOW() ),
('Zimatlán de Álvarez','20', NOW(), NOW() ),
('San Bernardo Mixtepec','20', NOW(), NOW() ),
('Santa Cruz Mixtepec','20', NOW(), NOW() ),
('San Miguel Mixtepec','20', NOW(), NOW() ),
('Santa María Atzompa','20', NOW(), NOW() ),
('San Andrés Ixtlahuaca','20', NOW(), NOW() ),
('Santa Cruz Amilpas','20', NOW(), NOW() ),
('Santa Lucía del Camino','20', NOW(), NOW() ),
('Santa Cruz Xoxocotlán','20', NOW(), NOW() ),
('San Pedro Ixtlahuaca','20', NOW(), NOW() ),
('San Antonio de la Cal','20', NOW(), NOW() ),
('San Agustín de las Juntas','20', NOW(), NOW() ),
('Cuilápam de Guerrero','20', NOW(), NOW() ),
('Ánimas Trujano','20', NOW(), NOW() ),
('San Sebastián Tutla','20', NOW(), NOW() ),
('San Raymundo Jalpan','20', NOW(), NOW() ),
('Villa de Zaachila','20', NOW(), NOW() ),
('Santa María Coyotepec','20', NOW(), NOW() ),
('San Bartolo Coyotepec','20', NOW(), NOW() ),
('Santa Inés Yatzeche','20', NOW(), NOW() ),
('Ciénega de Zimatlán','20', NOW(), NOW() ),
('San Antonio Huitepec','20', NOW(), NOW() ),
('Trinidad Zaachila','20', NOW(), NOW() ),
('San Pablo Huixtepec','20', NOW(), NOW() ),
('San Miguel Peras','20', NOW(), NOW() ),
('San Pablo Cuatro Venados','20', NOW(), NOW() ),
('Santa Inés del Monte','20', NOW(), NOW() ),
('Santa Gertrudis','20', NOW(), NOW() ),
('San Antonino el Alto','20', NOW(), NOW() ),
('Magdalena Mixtepec','20', NOW(), NOW() ),
('Santa Catarina Quiané','20', NOW(), NOW() ),
('Ayoquezco de Aldama','20', NOW(), NOW() ),
('Santa Ana Tlapacoyan','20', NOW(), NOW() ),
('Santa Cruz Zenzontepec','20', NOW(), NOW() ),
('San Francisco Cahuacuá','20', NOW(), NOW() ),
('Zapotitlán del Río','20', NOW(), NOW() ),
('Santiago Textitlán','20', NOW(), NOW() ),
('Santiago Amoltepec','20', NOW(), NOW() ),
('Santa María Zaniza','20', NOW(), NOW() ),
('Santo Domingo Teojomulco','20', NOW(), NOW() ),
('San Jacinto Tlacotepec','20', NOW(), NOW() ),
('Villa Sola de Vega','20', NOW(), NOW() ),
('Santa María Lachixío','20', NOW(), NOW() ),
('San Vicente Lachixío','20', NOW(), NOW() ),
('San Lorenzo Texmelúcan','20', NOW(), NOW() ),
('Santa María Sola','20', NOW(), NOW() ),
('San Francisco Sola','20', NOW(), NOW() ),
('San Ildefonso Sola','20', NOW(), NOW() ),
('Santiago Minas','20', NOW(), NOW() ),
('Heroica Ciudad de Ejutla de Crespo','20', NOW(), NOW() ),
('San Martín Tilcajete','20', NOW(), NOW() ),
('Santo Tomás Jalieza','20', NOW(), NOW() ),
('San Juan Chilateca','20', NOW(), NOW() ),
('Ocotlán de Morelos','20', NOW(), NOW() ),
('Santa Ana Zegache','20', NOW(), NOW() ),
('Santiago Apóstol','20', NOW(), NOW() ),
('San Antonino Castillo Velasco','20', NOW(), NOW() ),
('Asunción Ocotlán','20', NOW(), NOW() ),
('San Pedro Mártir','20', NOW(), NOW() ),
('San Dionisio Ocotlán','20', NOW(), NOW() ),
('Magdalena Ocotlán','20', NOW(), NOW() ),
('San Miguel Tilquiápam','20', NOW(), NOW() ),
('Santa Catarina Minas','20', NOW(), NOW() ),
('San Baltazar Chichicápam','20', NOW(), NOW() ),
('San Pedro Apóstol','20', NOW(), NOW() ),
('Santa Lucía Ocotlán','20', NOW(), NOW() ),
('San Jerónimo Taviche','20', NOW(), NOW() ),
('San Andrés Zabache','20', NOW(), NOW() ),
('San José del Progreso','20', NOW(), NOW() ),
('Yaxe','20', NOW(), NOW() ),
('San Pedro Taviche','20', NOW(), NOW() ),
('San Martín de los Cansecos','20', NOW(), NOW() ),
('San Martín Lachilá','20', NOW(), NOW() ),
('La Pe','20', NOW(), NOW() ),
('La Compañía','20', NOW(), NOW() ),
('Coatecas Altas','20', NOW(), NOW() ),
('San Juan Lachigalla','20', NOW(), NOW() ),
('San Agustín Amatengo','20', NOW(), NOW() ),
('Taniche','20', NOW(), NOW() ),
('San Miguel Ejutla','20', NOW(), NOW() ),
('Yogana','20', NOW(), NOW() ),
('San Vicente Coatlán','20', NOW(), NOW() ),
('Santiago Pinotepa Nacional','20', NOW(), NOW() ),
('San Juan Cacahuatepec','20', NOW(), NOW() ),
('San Juan Bautista Lo de Soto','20', NOW(), NOW() ),
('Mártires de Tacubaya','20', NOW(), NOW() ),
('San Sebastián Ixcapa','20', NOW(), NOW() ),
('San Antonio Tepetlapa','20', NOW(), NOW() ),
('Santa María Cortijo','20', NOW(), NOW() ),
('Santiago Llano Grande','20', NOW(), NOW() ),
('San Miguel Tlacamama','20', NOW(), NOW() ),
('Santiago Tapextla','20', NOW(), NOW() ),
('San José Estancia Grande','20', NOW(), NOW() ),
('Santo Domingo Armenta','20', NOW(), NOW() ),
('Santiago Jamiltepec','20', NOW(), NOW() ),
('San Pedro Atoyac','20', NOW(), NOW() ),
('San Juan Colorado','20', NOW(), NOW() ),
('Santiago Ixtayutla','20', NOW(), NOW() ),
('San Pedro Jicayán','20', NOW(), NOW() ),
('Pinotepa de Don Luis','20', NOW(), NOW() ),
('San Lorenzo','20', NOW(), NOW() ),
('San Agustín Chayuco','20', NOW(), NOW() ),
('San Andrés Huaxpaltepec','20', NOW(), NOW() ),
('Santa Catarina Mechoacán','20', NOW(), NOW() ),
('Santiago Tetepec','20', NOW(), NOW() ),
('Santa María Huazolotitlán','20', NOW(), NOW() ),
('Villa de Tututepec de Melchor Ocampo','20', NOW(), NOW() ),
('Tataltepec de Valdés','20', NOW(), NOW() ),
('San Juan Quiahije','20', NOW(), NOW() ),
('San Miguel Panixtlahuaca','20', NOW(), NOW() ),
('Santa Catarina Juquila','20', NOW(), NOW() ),
('San Pedro Juchatengo','20', NOW(), NOW() ),
('Santiago Yaitepec','20', NOW(), NOW() ),
('San Juan Lachao','20', NOW(), NOW() ),
('Santa María Temaxcaltepec','20', NOW(), NOW() ),
('Santos Reyes Nopala','20', NOW(), NOW() ),
('San Gabriel Mixtepec','20', NOW(), NOW() ),
('San Pedro Mixtepec -Dto. 22 -','20', NOW(), NOW() ),
('Monterrey','19', NOW(), NOW() ),
('Anáhuac','19', NOW(), NOW() ),
('Lampazos de Naranjo','19', NOW(), NOW() ),
('Mina','19', NOW(), NOW() ),
('Bustamante','19', NOW(), NOW() ),
('Sabinas Hidalgo','19', NOW(), NOW() ),
('Villaldama','19', NOW(), NOW() ),
('Vallecillo','19', NOW(), NOW() ),
('Parás','19', NOW(), NOW() ),
('Salinas Victoria','19', NOW(), NOW() ),
('Ciénega de Flores','19', NOW(), NOW() ),
('Hidalgo','19', NOW(), NOW() ),
('Abasolo','19', NOW(), NOW() ),
('Higueras','19', NOW(), NOW() ),
('Gral. Zuazua','19', NOW(), NOW() ),
('Agualeguas','19', NOW(), NOW() ),
('Gral. Treviño','19', NOW(), NOW() ),
('Cerralvo','19', NOW(), NOW() ),
('Melchor Ocampo','19', NOW(), NOW() ),
('García','19', NOW(), NOW() ),
('Gral. Escobedo','19', NOW(), NOW() ),
('Santa Catarina','19', NOW(), NOW() ),
('San Pedro Garza García','19', NOW(), NOW() ),
('San Nicolás de los Garza','19', NOW(), NOW() ),
('Carmen','19', NOW(), NOW() ),
('Apodaca','19', NOW(), NOW() ),
('Pesquería','19', NOW(), NOW() ),
('Marín','19', NOW(), NOW() ),
('Dr. González','19', NOW(), NOW() ),
('Los Ramones','19', NOW(), NOW() ),
('Los Herreras','19', NOW(), NOW() ),
('Los Aldamas','19', NOW(), NOW() ),
('Dr. Coss','19', NOW(), NOW() ),
('Gral. Bravo','19', NOW(), NOW() ),
('China','19', NOW(), NOW() ),
('Guadalupe','19', NOW(), NOW() ),
('Juárez','19', NOW(), NOW() ),
('Santiago','19', NOW(), NOW() ),
('Allende','19', NOW(), NOW() ),
('Gral. Terán','19', NOW(), NOW() ),
('Cadereyta Jiménez','19', NOW(), NOW() ),
('Montemorelos','19', NOW(), NOW() ),
('Rayones','19', NOW(), NOW() ),
('Linares','19', NOW(), NOW() ),
('Iturbide','19', NOW(), NOW() ),
('Galeana','19', NOW(), NOW() ),
('Hualahuises','19', NOW(), NOW() ),
('Dr. Arroyo','19', NOW(), NOW() ),
('Aramberri','19', NOW(), NOW() ),
('Gral. Zaragoza','19', NOW(), NOW() ),
('Mier y Noriega','19', NOW(), NOW() ),
('Tepic','18', NOW(), NOW() ),
('Tuxpan','18', NOW(), NOW() ),
('Santiago Ixcuintla','18', NOW(), NOW() ),
('Acaponeta','18', NOW(), NOW() ),
('Tecuala','18', NOW(), NOW() ),
('Huajicori','18', NOW(), NOW() ),
('Del Nayar','18', NOW(), NOW() ),
('La Yesca','18', NOW(), NOW() ),
('Ruíz','18', NOW(), NOW() ),
('Rosamorada','18', NOW(), NOW() ),
('Compostela','18', NOW(), NOW() ),
('Bahía de Banderas','18', NOW(), NOW() ),
('San Blas','18', NOW(), NOW() ),
('Xalisco','18', NOW(), NOW() ),
('San Pedro Lagunillas','18', NOW(), NOW() ),
('Santa María del Oro','18', NOW(), NOW() ),
('Jala','18', NOW(), NOW() ),
('Ahuacatlán','18', NOW(), NOW() ),
('Ixtlán del Río','18', NOW(), NOW() ),
('Amatlán de Cañas','18', NOW(), NOW() ),
('Zacatecas','32', NOW(), NOW() ),
('Morelos','32', NOW(), NOW() ),
('Vetagrande','32', NOW(), NOW() ),
('Concepción del Oro','32', NOW(), NOW() ),
('Melchor Ocampo','32', NOW(), NOW() ),
('Mazapil','32', NOW(), NOW() ),
('El Salvador','32', NOW(), NOW() ),
('Juan Aldama','32', NOW(), NOW() ),
('Miguel Auza','32', NOW(), NOW() ),
('General Francisco R. Murguía','32', NOW(), NOW() ),
('Río Grande','32', NOW(), NOW() ),
('Villa de Cos','32', NOW(), NOW() ),
('Cañitas de Felipe Pescador','32', NOW(), NOW() ),
('Calera','32', NOW(), NOW() ),
('Pánuco','32', NOW(), NOW() ),
('General Enrique Estrada','32', NOW(), NOW() ),
('Guadalupe','32', NOW(), NOW() ),
('Trancoso','32', NOW(), NOW() ),
('Genaro Codina','32', NOW(), NOW() ),
('Cuauhtémoc','32', NOW(), NOW() ),
('Ojocaliente','32', NOW(), NOW() ),
('General Pánfilo Natera','32', NOW(), NOW() ),
('Luis Moya','32', NOW(), NOW() ),
('Loreto','32', NOW(), NOW() ),
('Villa González Ortega','32', NOW(), NOW() ),
('Noria de Ángeles','32', NOW(), NOW() ),
('Villa García','32', NOW(), NOW() ),
('Pinos','32', NOW(), NOW() ),
('Villa Hidalgo','32', NOW(), NOW() ),
('Fresnillo','32', NOW(), NOW() ),
('Sombrerete','32', NOW(), NOW() ),
('Sain Alto','32', NOW(), NOW() ),
('Valparaíso','32', NOW(), NOW() ),
('Chalchihuites','32', NOW(), NOW() ),
('Jiménez del Teul','32', NOW(), NOW() ),
('Jerez','32', NOW(), NOW() ),
('Monte Escobedo','32', NOW(), NOW() ),
('Susticacán','32', NOW(), NOW() ),
('Villanueva','32', NOW(), NOW() ),
('Tepetongo','32', NOW(), NOW() ),
('El Plateado de Joaquín Amaro','32', NOW(), NOW() ),
('Jalpa','32', NOW(), NOW() ),
('Tabasco','32', NOW(), NOW() ),
('Huanusco','32', NOW(), NOW() ),
('Tlaltenango de Sánchez Román','32', NOW(), NOW() ),
('Momax','32', NOW(), NOW() ),
('Atolinga','32', NOW(), NOW() ),
('Tepechitlán','32', NOW(), NOW() ),
('Benito Juárez','32', NOW(), NOW() ),
('Teúl de González Ortega','32', NOW(), NOW() ),
('Santa María de la Paz','32', NOW(), NOW() ),
('Trinidad García de la Cadena','32', NOW(), NOW() ),
('Mezquital del Oro','32', NOW(), NOW() ),
('Nochistlán de Mejía','32', NOW(), NOW() ),
('Apulco','32', NOW(), NOW() ),
('Apozol','32', NOW(), NOW() ),
('Juchipila','32', NOW(), NOW() ),
('Moyahua de Estrada','32', NOW(), NOW() ),
('Aguascalientes','1', NOW(), NOW() ),
('San Francisco de los Romo','1', NOW(), NOW() ),
('El Llano','1', NOW(), NOW() ),
('Rincón de Romos','1', NOW(), NOW() ),
('Cosío','1', NOW(), NOW() ),
('San José de Gracia','1', NOW(), NOW() ),
('Tepezalá','1', NOW(), NOW() ),
('Pabellón de Arteaga','1', NOW(), NOW() ),
('Asientos','1', NOW(), NOW() ),
('Calvillo','1', NOW(), NOW() ),
('Jesús María','1', NOW(), NOW() ),
('Othón P. Blanco','23', NOW(), NOW() ),
('Felipe Carrillo Puerto','23', NOW(), NOW() ),
('Lázaro Cárdenas','23', NOW(), NOW() ),
('Isla Mujeres','23', NOW(), NOW() ),
('Benito Juárez','23', NOW(), NOW() ),
('Cozumel','23', NOW(), NOW() ),
('Solidaridad','23', NOW(), NOW() ),
('Tulum','23', NOW(), NOW() ),
('José María Morelos','23', NOW(), NOW() ),
('Tuxtla Gutiérrez','7', NOW(), NOW() ),
('San Fernando','7', NOW(), NOW() ),
('Berriozábal','7', NOW(), NOW() ),
('Ocozocoautla de Espinosa','7', NOW(), NOW() ),
('Suchiapa','7', NOW(), NOW() ),
('Chiapa de Corzo','7', NOW(), NOW() ),
('Osumacinta','7', NOW(), NOW() ),
('San Cristóbal de las Casas','7', NOW(), NOW() ),
('Chamula','7', NOW(), NOW() ),
('Ixtapa','7', NOW(), NOW() ),
('Zinacantán','7', NOW(), NOW() ),
('Acala','7', NOW(), NOW() ),
('Chiapilla','7', NOW(), NOW() ),
('San Lucas','7', NOW(), NOW() ),
('Teopisca','7', NOW(), NOW() ),
('Amatenango del Valle','7', NOW(), NOW() ),
('Chanal','7', NOW(), NOW() ),
('Oxchuc','7', NOW(), NOW() ),
('Huixtán','7', NOW(), NOW() ),
('Tenejapa','7', NOW(), NOW() ),
('Mitontic','7', NOW(), NOW() ),
('Reforma','7', NOW(), NOW() ),
('Juárez','7', NOW(), NOW() ),
('Pichucalco','7', NOW(), NOW() ),
('Sunuapa','7', NOW(), NOW() ),
('Ostuacán','7', NOW(), NOW() ),
('Francisco León','7', NOW(), NOW() ),
('Ixtacomitán','7', NOW(), NOW() ),
('Solosuchiapa','7', NOW(), NOW() ),
('Ixtapangajoya','7', NOW(), NOW() ),
('Tecpatán','7', NOW(), NOW() ),
('Copainalá','7', NOW(), NOW() ),
('Chicoasén','7', NOW(), NOW() ),
('Coapilla','7', NOW(), NOW() ),
('Pantepec','7', NOW(), NOW() ),
('Tapalapa','7', NOW(), NOW() ),
('Ocotepec','7', NOW(), NOW() ),
('Chapultenango','7', NOW(), NOW() ),
('Amatán','7', NOW(), NOW() ),
('Huitiupán','7', NOW(), NOW() ),
('Ixhuatán','7', NOW(), NOW() ),
('Tapilula','7', NOW(), NOW() ),
('Rayón','7', NOW(), NOW() ),
('Pueblo Nuevo Solistahuacán','7', NOW(), NOW() ),
('Jitotol','7', NOW(), NOW() ),
('Bochil','7', NOW(), NOW() ),
('Soyaló','7', NOW(), NOW() ),
('San Juan Cancuc','7', NOW(), NOW() ),
('Sabanilla','7', NOW(), NOW() ),
('Simojovel','7', NOW(), NOW() ),
('San Andrés Duraznal','7', NOW(), NOW() ),
('El Bosque','7', NOW(), NOW() ),
('Chalchihuitán','7', NOW(), NOW() ),
('Larráinzar','7', NOW(), NOW() ),
('Santiago el Pinar','7', NOW(), NOW() ),
('Chenalhó','7', NOW(), NOW() ),
('Aldama','7', NOW(), NOW() ),
('Pantelhó','7', NOW(), NOW() ),
('Sitalá','7', NOW(), NOW() ),
('Salto de Agua','7', NOW(), NOW() ),
('Tila','7', NOW(), NOW() ),
('Tumbalá','7', NOW(), NOW() ),
('Yajalón','7', NOW(), NOW() ),
('Chilón','7', NOW(), NOW() ),
('Ocosingo','7', NOW(), NOW() ),
('Benemérito de las Américas','7', NOW(), NOW() ),
('Marqués de Comillas','7', NOW(), NOW() ),
('Palenque','7', NOW(), NOW() ),
('La Libertad','7', NOW(), NOW() ),
('Catazajá','7', NOW(), NOW() ),
('Comitán de Domínguez','7', NOW(), NOW() ),
('Tzimol','7', NOW(), NOW() ),
('Chicomuselo','7', NOW(), NOW() ),
('Bella Vista','7', NOW(), NOW() ),
('Frontera Comalapa','7', NOW(), NOW() ),
('La Trinitaria','7', NOW(), NOW() ),
('La Independencia','7', NOW(), NOW() ),
('Maravilla Tenejapa','7', NOW(), NOW() ),
('Las Margaritas','7', NOW(), NOW() ),
('Altamirano','7', NOW(), NOW() ),
('Venustiano Carranza','7', NOW(), NOW() ),
('Totolapa','7', NOW(), NOW() ),
('Nicolás Ruíz','7', NOW(), NOW() ),
('Las Rosas','7', NOW(), NOW() ),
('La Concordia','7', NOW(), NOW() ),
('Angel Albino Corzo','7', NOW(), NOW() ),
('Montecristo de Guerrero','7', NOW(), NOW() ),
('Socoltenango','7', NOW(), NOW() ),
('Cintalapa','7', NOW(), NOW() ),
('Jiquipilas','7', NOW(), NOW() ),
('Arriaga','7', NOW(), NOW() ),
('Villaflores','7', NOW(), NOW() ),
('Tonalá','7', NOW(), NOW() ),
('Villa Corzo','7', NOW(), NOW() ),
('Pijijiapan','7', NOW(), NOW() ),
('Mapastepec','7', NOW(), NOW() ),
('Acapetahua','7', NOW(), NOW() ),
('Acacoyagua','7', NOW(), NOW() ),
('Escuintla','7', NOW(), NOW() ),
('Villa Comaltitlán','7', NOW(), NOW() ),
('Huixtla','7', NOW(), NOW() ),
('Mazatán','7', NOW(), NOW() ),
('Huehuetán','7', NOW(), NOW() ),
('Tuzantán','7', NOW(), NOW() ),
('Tapachula','7', NOW(), NOW() ),
('Suchiate','7', NOW(), NOW() ),
('Frontera Hidalgo','7', NOW(), NOW() ),
('Metapa','7', NOW(), NOW() ),
('Tuxtla Chico','7', NOW(), NOW() ),
('Unión Juárez','7', NOW(), NOW() ),
('Cacahoatán','7', NOW(), NOW() ),
('Motozintla','7', NOW(), NOW() ),
('Mazapa de Madero','7', NOW(), NOW() ),
('Amatenango de la Frontera','7', NOW(), NOW() ),
('Bejucal de Ocampo','7', NOW(), NOW() ),
('La Grandeza','7', NOW(), NOW() ),
('El Porvenir','7', NOW(), NOW() ),
('Siltepec','7', NOW(), NOW() ),
('Durango','10', NOW(), NOW() ),
('Canatlán','10', NOW(), NOW() ),
('Nuevo Ideal','10', NOW(), NOW() ),
('Coneto de Comonfort','10', NOW(), NOW() ),
('San Juan del Río','10', NOW(), NOW() ),
('Canelas','10', NOW(), NOW() ),
('Topia','10', NOW(), NOW() ),
('Tamazula','10', NOW(), NOW() ),
('Santiago Papasquiaro','10', NOW(), NOW() ),
('Otáez','10', NOW(), NOW() ),
('San Dimas','10', NOW(), NOW() ),
('Guadalupe Victoria','10', NOW(), NOW() ),
('Peñón Blanco','10', NOW(), NOW() ),
('Pánuco de Coronado','10', NOW(), NOW() ),
('Poanas','10', NOW(), NOW() ),
('Nombre de Dios','10', NOW(), NOW() ),
('Vicente Guerrero','10', NOW(), NOW() ),
('Súchil','10', NOW(), NOW() ),
('Pueblo Nuevo','10', NOW(), NOW() ),
('Mezquital','10', NOW(), NOW() ),
('Gómez Palacio','10', NOW(), NOW() ),
('Lerdo','10', NOW(), NOW() ),
('Mapimí','10', NOW(), NOW() ),
('Tlahualilo','10', NOW(), NOW() ),
('Hidalgo','10', NOW(), NOW() ),
('Ocampo','10', NOW(), NOW() ),
('Guanaceví','10', NOW(), NOW() ),
('San Bernardo','10', NOW(), NOW() ),
('Indé','10', NOW(), NOW() ),
('San Pedro del Gallo','10', NOW(), NOW() ),
('Tepehuanes','10', NOW(), NOW() ),
('El Oro','10', NOW(), NOW() ),
('Nazas','10', NOW(), NOW() ),
('San Luis del Cordero','10', NOW(), NOW() ),
('Rodeo','10', NOW(), NOW() ),
('Cuencamé','10', NOW(), NOW() ),
('Santa Clara','10', NOW(), NOW() ),
('San Juan de Guadalupe','10', NOW(), NOW() ),
('General Simón Bolívar','10', NOW(), NOW() ),
('Hermosillo','26', NOW(), NOW() ),
('San Miguel de Horcasitas','26', NOW(), NOW() ),
('Carbó','26', NOW(), NOW() ),
('San Luis Río Colorado','26', NOW(), NOW() ),
('Puerto Peñasco','26', NOW(), NOW() ),
('General Plutarco Elías Calles','26', NOW(), NOW() ),
('Caborca','26', NOW(), NOW() ),
('Altar','26', NOW(), NOW() ),
('Tubutama','26', NOW(), NOW() ),
('Atil','26', NOW(), NOW() ),
('Oquitoa','26', NOW(), NOW() ),
('Sáric','26', NOW(), NOW() ),
('Benjamín Hill','26', NOW(), NOW() ),
('Trincheras','26', NOW(), NOW() ),
('Pitiquito','26', NOW(), NOW() ),
('Nogales','26', NOW(), NOW() ),
('Imuris','26', NOW(), NOW() ),
('Santa Cruz','26', NOW(), NOW() ),
('Magdalena','26', NOW(), NOW() ),
('Naco','26', NOW(), NOW() ),
('Agua Prieta','26', NOW(), NOW() ),
('Fronteras','26', NOW(), NOW() ),
('Nacozari de García','26', NOW(), NOW() ),
('Bavispe','26', NOW(), NOW() ),
('Bacerac','26', NOW(), NOW() ),
('Huachinera','26', NOW(), NOW() ),
('Nácori Chico','26', NOW(), NOW() ),
('Granados','26', NOW(), NOW() ),
('Bacadéhuachi','26', NOW(), NOW() ),
('Cumpas','26', NOW(), NOW() ),
('Huásabas','26', NOW(), NOW() ),
('Moctezuma','26', NOW(), NOW() ),
('Villa Hidalgo','26', NOW(), NOW() ),
('Santa Ana','26', NOW(), NOW() ),
('Cananea','26', NOW(), NOW() ),
('Arizpe','26', NOW(), NOW() ),
('Cucurpe','26', NOW(), NOW() ),
('Bacoachi','26', NOW(), NOW() ),
('San Pedro de la Cueva','26', NOW(), NOW() ),
('Divisaderos','26', NOW(), NOW() ),
('Tepache','26', NOW(), NOW() ),
('Villa Pesqueira','26', NOW(), NOW() ),
('Opodepe','26', NOW(), NOW() ),
('Huépac','26', NOW(), NOW() ),
('Banámichi','26', NOW(), NOW() ),
('Ures','26', NOW(), NOW() ),
('Aconchi','26', NOW(), NOW() ),
('Baviácora','26', NOW(), NOW() ),
('San Felipe de Jesús','26', NOW(), NOW() ),
('Rayón','26', NOW(), NOW() ),
('Cajeme','26', NOW(), NOW() ),
('Navojoa','26', NOW(), NOW() ),
('Huatabampo','26', NOW(), NOW() ),
('Bácum','26', NOW(), NOW() ),
('Etchojoa','26', NOW(), NOW() ),
('Benito Juárez','26', NOW(), NOW() ),
('Empalme','26', NOW(), NOW() ),
('Guaymas','26', NOW(), NOW() ),
('San Ignacio Río Muerto','26', NOW(), NOW() ),
('La Colorada','26', NOW(), NOW() ),
('Mazatán','26', NOW(), NOW() ),
('Suaqui Grande','26', NOW(), NOW() ),
('Sahuaripa','26', NOW(), NOW() ),
('San Javier','26', NOW(), NOW() ),
('Soyopa','26', NOW(), NOW() ),
('Bacanora','26', NOW(), NOW() ),
('Arivechi','26', NOW(), NOW() ),
('Rosario','26', NOW(), NOW() ),
('Quiriego','26', NOW(), NOW() ),
('Onavas','26', NOW(), NOW() ),
('Alamos','26', NOW(), NOW() ),
('Yécora','26', NOW(), NOW() ),
('Álvaro Obregón','9', NOW(), NOW() ),
('Azcapotzalco','9', NOW(), NOW() ),
('Benito Juárez','9', NOW(), NOW() ),
('Coyoacán','9', NOW(), NOW() ),
('Cuajimalpa de Morelos','9', NOW(), NOW() ),
('Cuauhtémoc','9', NOW(), NOW() ),
('Gustavo A. Madero','9', NOW(), NOW() ),
('Iztacalco','9', NOW(), NOW() ),
('Iztapalapa','9', NOW(), NOW() ),
('La Magdalena Contreras','9', NOW(), NOW() ),
('Miguel Hidalgo','9', NOW(), NOW() ),
('Milpa Alta','9', NOW(), NOW() ),
('Tláhuac','9', NOW(), NOW() ),
('Tlalpan','9', NOW(), NOW() ),
('Venustiano Carranza','9', NOW(), NOW() ),
('Xochimilco','9', NOW(), NOW() ),
('Toluca','15', NOW(), NOW() ),
('Acambay','15', NOW(), NOW() ),
('Aculco','15', NOW(), NOW() ),
('Temascalcingo','15', NOW(), NOW() ),
('Atlacomulco','15', NOW(), NOW() ),
('Timilpan','15', NOW(), NOW() ),
('Morelos','15', NOW(), NOW() ),
('El Oro','15', NOW(), NOW() ),
('San Felipe del Progreso','15', NOW(), NOW() ),
('San José del Rincón','15', NOW(), NOW() ),
('Jocotitlán','15', NOW(), NOW() ),
('Ixtlahuaca','15', NOW(), NOW() ),
('Jiquipilco','15', NOW(), NOW() ),
('Temoaya','15', NOW(), NOW() ),
('Almoloya de Juárez','15', NOW(), NOW() ),
('Villa Victoria','15', NOW(), NOW() ),
('Villa de Allende','15', NOW(), NOW() ),
('Donato Guerra','15', NOW(), NOW() ),
('Ixtapan del Oro','15', NOW(), NOW() ),
('Santo Tomás','15', NOW(), NOW() ),
('Otzoloapan','15', NOW(), NOW() ),
('Zacazonapan','15', NOW(), NOW() ),
('Valle de Bravo','15', NOW(), NOW() ),
('Amanalco','15', NOW(), NOW() ),
('Temascaltepec','15', NOW(), NOW() ),
('Zinacantepec','15', NOW(), NOW() ),
('Tejupilco','15', NOW(), NOW() ),
('Luvianos','15', NOW(), NOW() ),
('San Simón de Guerrero','15', NOW(), NOW() ),
('Amatepec','15', NOW(), NOW() ),
('Tlatlaya','15', NOW(), NOW() ),
('Sultepec','15', NOW(), NOW() ),
('Texcaltitlán','15', NOW(), NOW() ),
('Coatepec Harinas','15', NOW(), NOW() ),
('Villa Guerrero','15', NOW(), NOW() ),
('Zacualpan','15', NOW(), NOW() ),
('Almoloya de Alquisiras','15', NOW(), NOW() ),
('Ixtapan de la Sal','15', NOW(), NOW() ),
('Tonatico','15', NOW(), NOW() ),
('Zumpahuacán','15', NOW(), NOW() ),
('Lerma','15', NOW(), NOW() ),
('Xonacatlán','15', NOW(), NOW() ),
('Otzolotepec','15', NOW(), NOW() ),
('San Mateo Atenco','15', NOW(), NOW() ),
('Metepec','15', NOW(), NOW() ),
('Mexicaltzingo','15', NOW(), NOW() ),
('Calimaya','15', NOW(), NOW() ),
('Chapultepec','15', NOW(), NOW() ),
('San Antonio la Isla','15', NOW(), NOW() ),
('Tenango del Valle','15', NOW(), NOW() ),
('Rayón','15', NOW(), NOW() ),
('Joquicingo','15', NOW(), NOW() ),
('Tenancingo','15', NOW(), NOW() ),
('Malinalco','15', NOW(), NOW() ),
('Ocuilan','15', NOW(), NOW() ),
('Atizapán','15', NOW(), NOW() ),
('Almoloya del Río','15', NOW(), NOW() ),
('Texcalyacac','15', NOW(), NOW() ),
('Tianguistenco','15', NOW(), NOW() ),
('Xalatlaco','15', NOW(), NOW() ),
('Capulhuac','15', NOW(), NOW() ),
('Ocoyoacac','15', NOW(), NOW() ),
('Huixquilucan','15', NOW(), NOW() ),
('Atizapán de Zaragoza','15', NOW(), NOW() ),
('Naucalpan de Juárez','15', NOW(), NOW() ),
('Tlalnepantla de Baz','15', NOW(), NOW() ),
('Polotitlán','15', NOW(), NOW() ),
('Jilotepec','15', NOW(), NOW() ),
('Soyaniquilpan de Juárez','15', NOW(), NOW() ),
('Villa del Carbón','15', NOW(), NOW() ),
('Chapa de Mota','15', NOW(), NOW() ),
('Nicolás Romero','15', NOW(), NOW() ),
('Isidro Fabela','15', NOW(), NOW() ),
('Jilotzingo','15', NOW(), NOW() ),
('Tepotzotlán','15', NOW(), NOW() ),
('Coyotepec','15', NOW(), NOW() ),
('Huehuetoca','15', NOW(), NOW() ),
('Cuautitlán Izcalli','15', NOW(), NOW() ),
('Teoloyucán','15', NOW(), NOW() ),
('Cuautitlán','15', NOW(), NOW() ),
('Melchor Ocampo','15', NOW(), NOW() ),
('Tultitlán','15', NOW(), NOW() ),
('Tultepec','15', NOW(), NOW() ),
('Ecatepec de Morelos','15', NOW(), NOW() ),
('Zumpango','15', NOW(), NOW() ),
('Tequixquiac','15', NOW(), NOW() ),
('Apaxco','15', NOW(), NOW() ),
('Hueypoxtla','15', NOW(), NOW() ),
('Coacalco de Berriozábal','15', NOW(), NOW() ),
('Tecámac','15', NOW(), NOW() ),
('Jaltenco','15', NOW(), NOW() ),
('Tonanitla','15', NOW(), NOW() ),
('Nextlalpan','15', NOW(), NOW() ),
('Teotihuacán','15', NOW(), NOW() ),
('San Martín de las Pirámides','15', NOW(), NOW() ),
('Acolman','15', NOW(), NOW() ),
('Otumba','15', NOW(), NOW() ),
('Axapusco','15', NOW(), NOW() ),
('Nopaltepec','15', NOW(), NOW() ),
('Temascalapa','15', NOW(), NOW() ),
('Tezoyuca','15', NOW(), NOW() ),
('Chiautla','15', NOW(), NOW() ),
('Papalotla','15', NOW(), NOW() ),
('Tepetlaoxtoc','15', NOW(), NOW() ),
('Texcoco','15', NOW(), NOW() ),
('Chiconcuac','15', NOW(), NOW() ),
('Atenco','15', NOW(), NOW() ),
('Chimalhuacán','15', NOW(), NOW() ),
('Chicoloapan','15', NOW(), NOW() ),
('La Paz','15', NOW(), NOW() ),
('Ixtapaluca','15', NOW(), NOW() ),
('Chalco','15', NOW(), NOW() ),
('Valle de Chalco Solidaridad','15', NOW(), NOW() ),
('Temamatla','15', NOW(), NOW() ),
('Cocotitlán','15', NOW(), NOW() ),
('Tlalmanalco','15', NOW(), NOW() ),
('Ayapango','15', NOW(), NOW() ),
('Tenango del Aire','15', NOW(), NOW() ),
('Ozumba','15', NOW(), NOW() ),
('Juchitepec','15', NOW(), NOW() ),
('Tepetlixpa','15', NOW(), NOW() ),
('Amecameca','15', NOW(), NOW() ),
('Atlautla','15', NOW(), NOW() ),
('Ecatzingo','15', NOW(), NOW() ),
('Nezahualcóyotl','15', NOW(), NOW() ),
('Campeche','4', NOW(), NOW() ),
('Carmen','4', NOW(), NOW() ),
('Palizada','4', NOW(), NOW() ),
('Candelaria','4', NOW(), NOW() ),
('Escárcega','4', NOW(), NOW() ),
('Champotón','4', NOW(), NOW() ),
('Hopelchén','4', NOW(), NOW() ),
('Calakmul','4', NOW(), NOW() ),
('Tenabo','4', NOW(), NOW() ),
('Hecelchakán','4', NOW(), NOW() ),
('Calkiní','4', NOW(), NOW() ),
('Centro','27', NOW(), NOW() ),
('Jalpa de Méndez','27', NOW(), NOW() ),
('Nacajuca','27', NOW(), NOW() ),
('Comalcalco','27', NOW(), NOW() ),
('Huimanguillo','27', NOW(), NOW() ),
('Cárdenas','27', NOW(), NOW() ),
('Paraíso','27', NOW(), NOW() ),
('Cunduacán','27', NOW(), NOW() ),
('Macuspana','27', NOW(), NOW() ),
('Centla','27', NOW(), NOW() ),
('Jonuta','27', NOW(), NOW() ),
('Teapa','27', NOW(), NOW() ),
('Jalapa','27', NOW(), NOW() ),
('Tacotalpa','27', NOW(), NOW() ),
('Tenosique','27', NOW(), NOW() ),
('Balancán','27', NOW(), NOW() ),
('Emiliano Zapata','27', NOW(), NOW() ),
('Morelia','16', NOW(), NOW() ),
('Huaniqueo','16', NOW(), NOW() ),
('Coeneo','16', NOW(), NOW() ),
('Quiroga','16', NOW(), NOW() ),
('Tzintzuntzan','16', NOW(), NOW() ),
('Lagunillas','16', NOW(), NOW() ),
('Acuitzio','16', NOW(), NOW() ),
('Madero','16', NOW(), NOW() ),
('Puruándiro','16', NOW(), NOW() ),
('José Sixto Verduzco','16', NOW(), NOW() ),
('Angamacutiro','16', NOW(), NOW() ),
('Panindícuaro','16', NOW(), NOW() ),
('Zacapu','16', NOW(), NOW() ),
('Tlazazalca','16', NOW(), NOW() ),
('Purépero','16', NOW(), NOW() ),
('Jiménez','16', NOW(), NOW() ),
('Morelos','16', NOW(), NOW() ),
('Huandacareo','16', NOW(), NOW() ),
('Cuitzeo','16', NOW(), NOW() ),
('Chucándiro','16', NOW(), NOW() ),
('Copándaro','16', NOW(), NOW() ),
('Tarímbaro','16', NOW(), NOW() ),
('Santa Ana Maya','16', NOW(), NOW() ),
('Álvaro Obregón','16', NOW(), NOW() ),
('Zinapécuaro','16', NOW(), NOW() ),
('Indaparapeo','16', NOW(), NOW() ),
('Queréndaro','16', NOW(), NOW() ),
('Sahuayo','16', NOW(), NOW() ),
('Briseñas','16', NOW(), NOW() ),
('Cojumatlán de Régules','16', NOW(), NOW() ),
('Venustiano Carranza','16', NOW(), NOW() ),
('Pajacuarán','16', NOW(), NOW() ),
('Vista Hermosa','16', NOW(), NOW() ),
('Tanhuato','16', NOW(), NOW() ),
('Yurécuaro','16', NOW(), NOW() ),
('Ixtlán','16', NOW(), NOW() ),
('La Piedad','16', NOW(), NOW() ),
('Numarán','16', NOW(), NOW() ),
('Churintzio','16', NOW(), NOW() ),
('Zináparo','16', NOW(), NOW() ),
('Penjamillo','16', NOW(), NOW() ),
('Marcos Castellanos','16', NOW(), NOW() ),
('Jiquilpan','16', NOW(), NOW() ),
('Villamar','16', NOW(), NOW() ),
('Chavinda','16', NOW(), NOW() ),
('Zamora','16', NOW(), NOW() ),
('Ecuandureo','16', NOW(), NOW() ),
('Tangancícuaro','16', NOW(), NOW() ),
('Chilchota','16', NOW(), NOW() ),
('Jacona','16', NOW(), NOW() ),
('Tangamandapio','16', NOW(), NOW() ),
('Cotija','16', NOW(), NOW() ),
('Tocumbo','16', NOW(), NOW() ),
('Tingüindín','16', NOW(), NOW() ),
('Uruapan','16', NOW(), NOW() ),
('Charapan','16', NOW(), NOW() ),
('Paracho','16', NOW(), NOW() ),
('Cherán','16', NOW(), NOW() ),
('Nahuatzen','16', NOW(), NOW() ),
('Tingambato','16', NOW(), NOW() ),
('Los Reyes','16', NOW(), NOW() ),
('Peribán','16', NOW(), NOW() ),
('Tancítaro','16', NOW(), NOW() ),
('Nuevo Parangaricutiro','16', NOW(), NOW() ),
('Buenavista','16', NOW(), NOW() ),
('Tepalcatepec','16', NOW(), NOW() ),
('Aguililla','16', NOW(), NOW() ),
('Apatzingán','16', NOW(), NOW() ),
('Parácuaro','16', NOW(), NOW() ),
('Coahuayana','16', NOW(), NOW() ),
('Chinicuila','16', NOW(), NOW() ),
('Coalcomán de Vázquez Pallares','16', NOW(), NOW() ),
('Aquila','16', NOW(), NOW() ),
('Tumbiscatío','16', NOW(), NOW() ),
('Arteaga','16', NOW(), NOW() ),
('Lázaro Cárdenas','16', NOW(), NOW() ),
('Epitacio Huerta','16', NOW(), NOW() ),
('Contepec','16', NOW(), NOW() ),
('Tlalpujahua','16', NOW(), NOW() ),
('Hidalgo','16', NOW(), NOW() ),
('Maravatío','16', NOW(), NOW() ),
('Irimbo','16', NOW(), NOW() ),
('Senguio','16', NOW(), NOW() ),
('Charo','16', NOW(), NOW() ),
('Tzitzio','16', NOW(), NOW() ),
('Tiquicheo de Nicolás Romero','16', NOW(), NOW() ),
('Aporo','16', NOW(), NOW() ),
('Angangueo','16', NOW(), NOW() ),
('Tuxpan','16', NOW(), NOW() ),
('Ocampo','16', NOW(), NOW() ),
('Jungapeo','16', NOW(), NOW() ),
('Zitácuaro','16', NOW(), NOW() ),
('Tuzantla','16', NOW(), NOW() ),
('Juárez','16', NOW(), NOW() ),
('Susupuato','16', NOW(), NOW() ),
('Pátzcuaro','16', NOW(), NOW() ),
('Erongarícuaro','16', NOW(), NOW() ),
('Huiramba','16', NOW(), NOW() ),
('Tacámbaro','16', NOW(), NOW() ),
('Turicato','16', NOW(), NOW() ),
('Ziracuaretiro','16', NOW(), NOW() ),
('Taretan','16', NOW(), NOW() ),
('Gabriel Zamora','16', NOW(), NOW() ),
('Nuevo Urecho','16', NOW(), NOW() ),
('Múgica','16', NOW(), NOW() ),
('Salvador Escalante','16', NOW(), NOW() ),
('Ario','16', NOW(), NOW() ),
('La Huacana','16', NOW(), NOW() ),
('Churumuco','16', NOW(), NOW() ),
('Nocupétaro','16', NOW(), NOW() ),
('Carácuaro','16', NOW(), NOW() ),
('Huetamo','16', NOW(), NOW() ),
('San Lucas','16', NOW(), NOW() ),
('Xalapa','30', NOW(), NOW() ),
('Tlalnelhuayocan','30', NOW(), NOW() ),
('Xico','30', NOW(), NOW() ),
('Ixhuacán de los Reyes','30', NOW(), NOW() ),
('Ayahualulco','30', NOW(), NOW() ),
('Perote','30', NOW(), NOW() ),
('Banderilla','30', NOW(), NOW() ),
('Rafael Lucio','30', NOW(), NOW() ),
('Acajete','30', NOW(), NOW() ),
('Las Vigas de Ramírez','30', NOW(), NOW() ),
('Villa Aldama','30', NOW(), NOW() ),
('Tlacolulan','30', NOW(), NOW() ),
('Tonayán','30', NOW(), NOW() ),
('Coacoatzintla','30', NOW(), NOW() ),
('Jilotepec','30', NOW(), NOW() ),
('Naolinco','30', NOW(), NOW() ),
('Miahuatlán','30', NOW(), NOW() ),
('Acatlán','30', NOW(), NOW() ),
('Tepetlán','30', NOW(), NOW() ),
('Juchique de Ferrer','30', NOW(), NOW() ),
('Alto Lucero de Gutiérrez Barrios','30', NOW(), NOW() ),
('Actopan','30', NOW(), NOW() ),
('Coatepec','30', NOW(), NOW() ),
('Teocelo','30', NOW(), NOW() ),
('Cosautlán de Carvajal','30', NOW(), NOW() ),
('Emiliano Zapata','30', NOW(), NOW() ),
('Apazapan','30', NOW(), NOW() ),
('Puente Nacional','30', NOW(), NOW() ),
('Ursulo Galván','30', NOW(), NOW() ),
('Paso de Ovejas','30', NOW(), NOW() ),
('La Antigua','30', NOW(), NOW() ),
('Veracruz','30', NOW(), NOW() ),
('Pánuco','30', NOW(), NOW() ),
('Pueblo Viejo','30', NOW(), NOW() ),
('Tampico Alto','30', NOW(), NOW() ),
('Tempoal','30', NOW(), NOW() ),
('Ozuluama de Mascareñas','30', NOW(), NOW() ),
('Tantoyuca','30', NOW(), NOW() ),
('Platón Sánchez','30', NOW(), NOW() ),
('Chiconamel','30', NOW(), NOW() ),
('Chalma','30', NOW(), NOW() ),
('Chontla','30', NOW(), NOW() ),
('Citlaltépetl','30', NOW(), NOW() ),
('Ixcatepec','30', NOW(), NOW() ),
('Naranjos Amatlán','30', NOW(), NOW() ),
('El Higo','30', NOW(), NOW() ),
('Chinampa de Gorostiza','30', NOW(), NOW() ),
('Tantima','30', NOW(), NOW() ),
('Tamalín','30', NOW(), NOW() ),
('Cerro Azul','30', NOW(), NOW() ),
('Tepetzintla','30', NOW(), NOW() ),
('Tancoco','30', NOW(), NOW() ),
('Tamiahua','30', NOW(), NOW() ),
('Huayacocotla','30', NOW(), NOW() ),
('Ilamatlán','30', NOW(), NOW() ),
('Zontecomatlán de López y Fuentes','30', NOW(), NOW() ),
('Texcatepec','30', NOW(), NOW() ),
('Zacualpan','30', NOW(), NOW() ),
('Benito Juárez','30', NOW(), NOW() ),
('Tlachichilco','30', NOW(), NOW() ),
('Ixhuatlán de Madero','30', NOW(), NOW() ),
('Chicontepec','30', NOW(), NOW() ),
('Álamo Temapache','30', NOW(), NOW() ),
('Tuxpan','30', NOW(), NOW() ),
('Tihuatlán','30', NOW(), NOW() ),
('Castillo de Teayo','30', NOW(), NOW() ),
('Cazones de Herrera','30', NOW(), NOW() ),
('Zozocolco de Hidalgo','30', NOW(), NOW() ),
('Chumatlán','30', NOW(), NOW() ),
('Coxquihui','30', NOW(), NOW() ),
('Mecatlán','30', NOW(), NOW() ),
('Filomeno Mata','30', NOW(), NOW() ),
('Coahuitlán','30', NOW(), NOW() ),
('Coyutla','30', NOW(), NOW() ),
('Coatzintla','30', NOW(), NOW() ),
('Espinal','30', NOW(), NOW() ),
('Poza Rica de Hidalgo','30', NOW(), NOW() ),
('Papantla','30', NOW(), NOW() ),
('Gutiérrez Zamora','30', NOW(), NOW() ),
('Tecolutla','30', NOW(), NOW() ),
('Martínez de la Torre','30', NOW(), NOW() ),
('San Rafael','30', NOW(), NOW() ),
('Tlapacoyan','30', NOW(), NOW() ),
('Jalacingo','30', NOW(), NOW() ),
('Atzalan','30', NOW(), NOW() ),
('Altotonga','30', NOW(), NOW() ),
('Las Minas','30', NOW(), NOW() ),
('Tatatila','30', NOW(), NOW() ),
('Tenochtitlán','30', NOW(), NOW() ),
('Nautla','30', NOW(), NOW() ),
('Misantla','30', NOW(), NOW() ),
('Landero y Coss','30', NOW(), NOW() ),
('Chiconquiaco','30', NOW(), NOW() ),
('Yecuatla','30', NOW(), NOW() ),
('Colipa','30', NOW(), NOW() ),
('Vega de Alatorre','30', NOW(), NOW() ),
('Jalcomulco','30', NOW(), NOW() ),
('Tlaltetela','30', NOW(), NOW() ),
('Tenampa','30', NOW(), NOW() ),
('Totutla','30', NOW(), NOW() ),
('Sochiapa','30', NOW(), NOW() ),
('Tlacotepec de Mejía','30', NOW(), NOW() ),
('Huatusco','30', NOW(), NOW() ),
('Calcahualco','30', NOW(), NOW() ),
('Alpatláhuac','30', NOW(), NOW() ),
('Coscomatepec','30', NOW(), NOW() ),
('La Perla','30', NOW(), NOW() ),
('Chocamán','30', NOW(), NOW() ),
('Tomatlán','30', NOW(), NOW() ),
('Ixhuatlán del Café','30', NOW(), NOW() ),
('Tepatlaxco','30', NOW(), NOW() ),
('Comapa','30', NOW(), NOW() ),
('Zentla','30', NOW(), NOW() ),
('Camarón de Tejeda','30', NOW(), NOW() ),
('Soledad de Doblado','30', NOW(), NOW() ),
('Manlio Fabio Altamirano','30', NOW(), NOW() ),
('Jamapa','30', NOW(), NOW() ),
('Medellín','30', NOW(), NOW() ),
('Boca del Río','30', NOW(), NOW() ),
('Orizaba','30', NOW(), NOW() ),
('Rafael Delgado','30', NOW(), NOW() ),
('Mariano Escobedo','30', NOW(), NOW() ),
('Ixhuatlancillo','30', NOW(), NOW() ),
('Atzacan','30', NOW(), NOW() ),
('Ixtaczoquitlán','30', NOW(), NOW() ),
('Fortín','30', NOW(), NOW() ),
('Córdoba','30', NOW(), NOW() ),
('Maltrata','30', NOW(), NOW() ),
('Nogales','30', NOW(), NOW() ),
('Río Blanco','30', NOW(), NOW() ),
('Camerino Z. Mendoza','30', NOW(), NOW() ),
('Aquila','30', NOW(), NOW() ),
('Acultzingo','30', NOW(), NOW() ),
('Soledad Atzompa','30', NOW(), NOW() ),
('Huiloapan de Cuauhtémoc','30', NOW(), NOW() ),
('Tlaquilpa','30', NOW(), NOW() ),
('Astacinga','30', NOW(), NOW() ),
('Xoxocotla','30', NOW(), NOW() ),
('Atlahuilco','30', NOW(), NOW() ),
('Tequila','30', NOW(), NOW() ),
('San Andrés Tenejapan','30', NOW(), NOW() ),
('Tlilapan','30', NOW(), NOW() ),
('Magdalena','30', NOW(), NOW() ),
('Naranjal','30', NOW(), NOW() ),
('Coetzala','30', NOW(), NOW() ),
('Omealca','30', NOW(), NOW() ),
('Cuitláhuac','30', NOW(), NOW() ),
('Cuichapa','30', NOW(), NOW() ),
('Yanga','30', NOW(), NOW() ),
('Amatlán de los Reyes','30', NOW(), NOW() ),
('Atoyac','30', NOW(), NOW() ),
('Paso del Macho','30', NOW(), NOW() ),
('Carrillo Puerto','30', NOW(), NOW() ),
('Cotaxtla','30', NOW(), NOW() ),
('Zongolica','30', NOW(), NOW() ),
('Tehuipango','30', NOW(), NOW() ),
('Mixtla de Altamirano','30', NOW(), NOW() ),
('Los Reyes','30', NOW(), NOW() ),
('Texhuacán','30', NOW(), NOW() ),
('Tezonapa','30', NOW(), NOW() ),
('Tierra Blanca','30', NOW(), NOW() ),
('Tlalixcoyan','30', NOW(), NOW() ),
('Ignacio de la Llave','30', NOW(), NOW() ),
('Alvarado','30', NOW(), NOW() ),
('Lerdo de Tejada','30', NOW(), NOW() ),
('Tres Valles','30', NOW(), NOW() ),
('Carlos A. Carrillo','30', NOW(), NOW() ),
('Cosamaloapan de Carpio','30', NOW(), NOW() ),
('Ixmatlahuacan','30', NOW(), NOW() ),
('Acula','30', NOW(), NOW() ),
('Amatitlán','30', NOW(), NOW() ),
('Tlacotalpan','30', NOW(), NOW() ),
('Saltabarranca','30', NOW(), NOW() ),
('Otatitlán','30', NOW(), NOW() ),
('Tlacojalpan','30', NOW(), NOW() ),
('Tuxtilla','30', NOW(), NOW() ),
('Chacaltianguis','30', NOW(), NOW() ),
('José Azueta','30', NOW(), NOW() ),
('Playa Vicente','30', NOW(), NOW() ),
('Santiago Sochiapan','30', NOW(), NOW() ),
('Isla','30', NOW(), NOW() ),
('Juan Rodríguez Clara','30', NOW(), NOW() ),
('San Andrés Tuxtla','30', NOW(), NOW() ),
('Santiago Tuxtla','30', NOW(), NOW() ),
('Angel R. Cabada','30', NOW(), NOW() ),
('Hueyapan de Ocampo','30', NOW(), NOW() ),
('Catemaco','30', NOW(), NOW() ),
('Soteapan','30', NOW(), NOW() ),
('Mecayapan','30', NOW(), NOW() ),
('Tatahuicapan de Juárez','30', NOW(), NOW() ),
('Pajapan','30', NOW(), NOW() ),
('Chinameca','30', NOW(), NOW() ),
('Acayucan','30', NOW(), NOW() ),
('San Juan Evangelista','30', NOW(), NOW() ),
('Sayula de Alemán','30', NOW(), NOW() ),
('Oluta','30', NOW(), NOW() ),
('Soconusco','30', NOW(), NOW() ),
('Texistepec','30', NOW(), NOW() ),
('Jáltipan','30', NOW(), NOW() ),
('Zaragoza','30', NOW(), NOW() ),
('Oteapan','30', NOW(), NOW() ),
('Cosoleacaque','30', NOW(), NOW() ),
('Nanchital de Lázaro Cárdenas del Río','30', NOW(), NOW() ),
('Ixhuatlán del Sureste','30', NOW(), NOW() ),
('Moloacán','30', NOW(), NOW() ),
('Coatzacoalcos','30', NOW(), NOW() ),
('Agua Dulce','30', NOW(), NOW() ),
('Minatitlán','30', NOW(), NOW() ),
('Hidalgotitlán','30', NOW(), NOW() ),
('Jesús Carranza','30', NOW(), NOW() ),
('Las Choapas','30', NOW(), NOW() ),
('Uxpanapa','30', NOW(), NOW() ),
('Querétaro','22', NOW(), NOW() ),
('El Marqués','22', NOW(), NOW() ),
('Colón','22', NOW(), NOW() ),
('Pinal de Amoles','22', NOW(), NOW() ),
('Jalpan de Serra','22', NOW(), NOW() ),
('Landa de Matamoros','22', NOW(), NOW() ),
('Arroyo Seco','22', NOW(), NOW() ),
('Peñamiller','22', NOW(), NOW() ),
('Cadereyta de Montes','22', NOW(), NOW() ),
('San Joaquín','22', NOW(), NOW() ),
('Tolimán','22', NOW(), NOW() ),
('Ezequiel Montes','22', NOW(), NOW() ),
('Pedro Escobedo','22', NOW(), NOW() ),
('Tequisquiapan','22', NOW(), NOW() ),
('San Juan del Río','22', NOW(), NOW() ),
('Amealco de Bonfil','22', NOW(), NOW() ),
('Corregidora','22', NOW(), NOW() ),
('Huimilpan','22', NOW(), NOW());