INSERT INTO `statuses` (`status_category_id`, `name`, `priority`, `slack_days`, `created`, `updated`) VALUES
('1','Esta en el trabajo','0','0', NOW(), NOW() ),
('1','+ de 3 intentos sin poder hablar','0','0', NOW(), NOW() ),
('1','Recado','0','0', NOW(), NOW() ),
('1','No puede contestar','0','0', NOW(), NOW() ),
('1','No se encuentra','0','0', NOW(), NOW() ),
('2','Venta','0','0', NOW(), NOW() ),
('2','Realizó pago','1','7', NOW(), NOW() ),
('2','Cita agendada','0','0', NOW(), NOW() ),
('2','No llamar, el nos llama','0','0', NOW(), NOW() ),
('2','No interesado','0','0', NOW(), NOW() ),
('2','Ya vino a informes','3','7', NOW(), NOW() ),
('2','En seguimiento','5','7', NOW(), NOW() ),
('2','Interesado','4','10', NOW(), NOW() ),
('3','Teléfono y correo no existen','0','0', NOW(), NOW() ),
('3','No lo conocen','0','0', NOW(), NOW() ),
('3','Evidente','0','0', NOW(), NOW() ),
('3','Duplicado','0','0', NOW(), NOW() ),
('4','+ de 3 intentos sin contacto','0','0', NOW(), NOW() ),
('4','Teléfono ocupado/Nadie contesta','0','0', NOW(), NOW() ),
('4','Contesta grabadora','0','0', NOW(), NOW() ),
('1','No le interesa','0','0', NOW(), NOW() );
