INSERT INTO `states` (`name`, `created`, `updated`) VALUES
('Aguascalientes', NOW(), NOW() ),
('Baja California', NOW(), NOW()),
('Baja California Sur', NOW(), NOW()),
('Campeche', NOW(), NOW()),
('Coahuila', NOW(), NOW()),
('Colima', NOW(), NOW()),
('Chiapas', NOW(), NOW()),
('Chihuahua', NOW(), NOW()),
('Distrito Federal', NOW(), NOW()),
('Durango', NOW(), NOW()),
('Guanajuato', NOW(), NOW()),
('Guerrero', NOW(), NOW()),
('Hidalgo', NOW(), NOW()),
('Jalisco', NOW(), NOW()),
('México', NOW(), NOW()),
('Michoacan', NOW(), NOW()),
('Morelos', NOW(), NOW()),
('Nayarit', NOW(), NOW()),
('Nuevo León', NOW(), NOW()),
('Oaxaca', NOW(), NOW()),
('Puebla', NOW(), NOW()),
('Queretaro', NOW(), NOW()),
('Quintana Roo', NOW(), NOW()),
('San Luis Potosi', NOW(), NOW()),
('Sinaloa', NOW(), NOW()),
('Sonora', NOW(), NOW()),
('Tabasco', NOW(), NOW()),
('Tamaulipas', NOW(), NOW()),
('Tlaxcala', NOW(), NOW()),
('Veracruz', NOW(), NOW()),
('Yucatan', NOW(), NOW()),
('Zacatecas', NOW(), NOW());